CODEOWNERS
Add code owners. 
And first open source PR 🎉
=> docs(codeowners): add codeowners

README.md
Fix legacy url of github pages
=> docs(readme): fix url GH pages

src/components/typography/Text/Text.test.tsx, src/components/typography/Text/Text.tsx, src/components/typography/Text/__snapshots__/Text.test.tsx.snap
=> fix(text): fix types and default size value

src/components/organisms/Accordion/Accordion.md, src/components/organisms/Accordion/AccordionHeader/AccordionHeader.tsx
Add support for different sized headers on the accordion component. 
https://marvelapp.com/9hj9j4b/screen/48163664
=> fix(accordion): add support for different header sizes

src/components/atoms/Button/Button.tsx, src/components/atoms/Button/__snapshots__/Button.test.tsx.snap
We currently don't have any focus states implemented on the buttons, this will fix that. Apart for on link buttons, I didn't know how we want that to look so I left them with the outline. 
https://marvelapp.com/9hj9j4b/screen/48163664
=> fix(button): add focus state to buttons

etc/rollup/config.js
=> Point to the right version of `core-js` 😇

src/components/molecules/Modal/Modal.md, styleguide.config.js
Fix InputText name in the sidebar and improve modal docs
=> Improve docs

yarn.lock
Got out of date as part of the last PRs 💅🏻
=> Update lock file 🔓

src/components/atoms/Button/Button.tsx, src/components/atoms/Button/__snapshots__/Button.test.tsx.snap
Sorry... slipped through as part of my last PR 🤠 #77
=> 🔥 `!important`

package.json
This just adds a **commit** and a **Git tag**.
I plan to publish the `beta` on NPM ( if I don't run into _permission issues_ ).
I'm unsure whether doing the commit manually will conflict with `semantic-release`, although is something we can always drop later 👍🏻
You'll be able to grab the beta by:
```
yarn add @zopauk/react-components@next
```
=> Beta release ⚛︎

package.json, src/components/atoms/Button/Button.tsx, src/components/atoms/Button/__snapshots__/Button.test.tsx.snap, src/components/atoms/Heading/Heading.tsx, src/components/atoms/Link/Link.md, src/components/atoms/Link/Link.tsx, src/components/atoms/Link/__snapshots__/Link.test.tsx.snap, src/components/atoms/Text/Text.tsx, src/components/molecules/Help/__snapshots__/Help.test.tsx.snap, src/components/molecules/ZopaFooter/FooterLink/__snapshots__/FooterLink.test.tsx.snap, src/components/molecules/ZopaFooter/Links/__snapshots__/Links.test.tsx.snap, src/components/molecules/ZopaFooter/SocialLinks/__snapshots__/SocialLinks.test.tsx.snap, src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap, src/components/organisms/Accordion/context/AccordionContext.ts, src/constants/colors.ts
=> More tweaks 🤖 🛀

package.json, src/components/atoms/Badge/Badge.md, src/components/atoms/Badge/Badge.tsx, src/components/atoms/Badge/__snapshots__/Badge.test.tsx.snap, src/components/atoms/Button/Button.tsx, src/components/atoms/Button/__snapshots__/Button.test.tsx.snap, src/components/atoms/ErrorMessage/ErrorMessage.tsx, src/components/atoms/ErrorMessage/__snapshots__/ErrorMessage.test.tsx.snap, src/components/atoms/InputText/InputText.tsx, src/components/atoms/InputText/__snapshots__/InputText.test.tsx.snap, src/components/molecules/DropdownFiltered/DropdownFiltered.tsx, src/components/molecules/DropdownFiltered/__snapshots__/DropdownFiltered.test.tsx.snap, src/components/molecules/RadioField/RadioField.tsx, src/components/molecules/RadioField/__snapshots__/RadioField.test.tsx.snap, src/components/molecules/TextField/__snapshots__/TextField.test.tsx.snap, src/components/molecules/ZopaFooter/SocialLinks/SocialLinks.tsx, src/components/types.ts
Few refinements learnt when trying this `2.0.0` on one of our apps:
- use the old **padding** on `<Button />` for now
- fix the **padding** on `<Badge />` so its balanced on all sides
- make `<ErrorMessage />` small
- fix `<DropdownFiltered />` arrow positioning
- make `<Radiofiled />` text normal size again
=> More pre-release refinements 💅🏻

README.md, etc/docs/migration-v2.md
I wrote _extensive_ documentation on how to migrate to `2.0.0`.
It contains two sections:
- **Overview**
- **Primer**
**Overview** contains the details of the migration but most people will refer to the **Primer** to get their apps up to date quickly 🏎
It can be previewed [here](https://github.com/zopaUK/react-components/blob/docs/v2-migration-guide/etc/docs/migration-v2.md).
( _I also updated the main `README.md` to point to it and took the opportunity to clean it up a bit_ )
=> Add migrations docs 📚

src/components/molecules/ZopaFooter/Links/Links.tsx, src/components/molecules/ZopaFooter/Links/__snapshots__/Links.test.tsx.snap, src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
released to soon, auto team requested a temporary rollback
=> feat(zopafooter): car finance link removed

package.json, src/components/atoms/Badge/__snapshots__/Badge.test.tsx.snap, src/components/atoms/ErrorMessage/__snapshots__/ErrorMessage.test.tsx.snap, src/components/atoms/InputLabel/__snapshots__/InputLabel.test.tsx.snap, src/components/atoms/Link/__snapshots__/Link.test.tsx.snap, src/components/molecules/CheckboxField/__snapshots__/CheckboxField.test.tsx.snap, src/components/molecules/DropdownField/__snapshots__/DropdownField.test.tsx.snap, src/components/molecules/DropdownFiltered/__snapshots__/DropdownFiltered.test.tsx.snap, src/components/molecules/Help/__snapshots__/Help.test.tsx.snap, src/components/molecules/RadioField/__snapshots__/RadioField.test.tsx.snap, src/components/molecules/TextField/__snapshots__/TextField.test.tsx.snap, src/components/molecules/ZopaFooter/FooterLink/__snapshots__/FooterLink.test.tsx.snap, src/components/molecules/ZopaFooter/Legal/__snapshots__/Legal.test.tsx.snap, src/components/molecules/ZopaFooter/Links/__snapshots__/Links.test.tsx.snap, src/components/molecules/ZopaFooter/SocialLinks/__snapshots__/SocialLinks.test.tsx.snap, src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap, src/components/organisms/Accordion/AccordionHeader/__snapshots__/AccordionHeader.test.tsx.snap, src/components/organisms/Navbar/NavbarLink/__snapshots__/NavbarLink.test.tsx.snap, yarn.lock
update it to be a version after 4.3 since that's when forwardedAs was introduced.
=> fix(peer dependencies): move styled components to peer dependencies

src/components/molecules/ZopaFooter/ZopaFooter.tsx, src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
Update the footer background colour to use the new brand colours.
=> fix(footer background): change to background colour from brand

README.md
=> Remove reference to Alverata in README 🔪

yarn.lock
Just minor upgrades ( `x.^.x` ), doing a separate PR for major upgrades.
=> Minor dependency updates 🚁

src/components/atoms/Button/Button.tsx, src/components/atoms/Button/__snapshots__/Button.test.tsx.snap, yarn.lock
=> fix(button): add styles for button with as prop

src/components/molecules/ZopaFooter/Links/Links.tsx, src/components/molecules/ZopaFooter/Links/__snapshots__/Links.test.tsx.snap, src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
Somehow the privacy policy was mising from the footer
=> Restore privacy policy

src/components/molecules/ZopaFooter/Links/Links.tsx, src/components/molecules/ZopaFooter/Links/__snapshots__/Links.test.tsx.snap, src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
https://jira.zopa/browse/SHOPDEV-3243
=> feat(zopafooter): added link to p2p principles

src/components/hooks/useAccordion/useAccordion.test.ts, src/components/hooks/useAccordion/useAccordion.ts
Fix the issue of accordion not opening when multiple instances present
=> fix(accordion): fix accordion not opening

src/components/hooks/useForm/useForm.test.ts, src/components/hooks/useForm/useForm.ts, src/components/organisms/Form/Form/Form.test.tsx, src/components/organisms/Form/Form/Form.tsx, src/components/organisms/Form/FormButton/FormButton.test.tsx, src/components/organisms/Form/FormCheckboxField/FormCheckboxField.test.tsx, src/components/organisms/Form/FormDropdownField/FormDropdownField.test.tsx, src/components/organisms/Form/FormDropdownFilteredField/FormDropdownFilteredField.test.tsx, src/components/organisms/Form/FormRadioField/FormRadioField.test.tsx, src/components/organisms/Form/FormTextField/FormTextField.test.tsx
- fix `Form` interface
- make validate either async or sync
=> Improve form types and add a possibility for validate to be async

src/components/atoms/Link/Link.tsx, src/components/atoms/Link/__snapshots__/Link.test.tsx.snap, src/components/molecules/Help/__snapshots__/Help.test.tsx.snap, src/components/molecules/ZopaFooter/FooterLink/__snapshots__/FooterLink.test.tsx.snap, src/components/molecules/ZopaFooter/Links/__snapshots__/Links.test.tsx.snap, src/components/molecules/ZopaFooter/SocialLinks/__snapshots__/SocialLinks.test.tsx.snap, src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap, src/components/organisms/Navbar/NavbarLink/__snapshots__/NavbarLink.test.tsx.snap
=> fix(link): link not wrapping text

src/index.ts, yarn.lock
export grid constants to be consumed
fix #149
=> feat(grid): export grid constants

src/components/molecules/ExpiryModal/ExpiryModal.md, src/components/molecules/ExpiryModal/ExpiryModal.test.tsx, src/components/molecules/ExpiryModal/ExpiryModal.tsx, src/components/molecules/Modal/Modal.tsx, src/index.ts
New `<ExpiryModal />` molecule which in turn is just a wrapper around our standard `<Modal />` component with a given set of copy and styles 💅🏻 ✍️
<div align="center"><img src="https://user-images.githubusercontent.com/5938217/71010095-a2dcbc80-20eb-11ea-8c23-7cc4a080cd8b.png" width="200" /></div>
=> New <ExpiryModal /> 🔐 💭

src/components/molecules/ZopaFooter/FooterLink/FooterLink.tsx, src/components/molecules/ZopaFooter/FooterLink/__snapshots__/FooterLink.test.tsx.snap, src/components/molecules/ZopaFooter/Links/__snapshots__/Links.test.tsx.snap, src/components/molecules/ZopaFooter/SocialLinks/__snapshots__/SocialLinks.test.tsx.snap, src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
Now **Google Lighthouse** is happy 😊 , addressing #146
=> Increase tap targets on <ZopaFooter />

package.json, src/components/atoms/InputText/InputText.tsx
Types for `<InputText />` weren't set correctly 😓
=> Fix `<InputText />` types

src/components/hooks/useForm/useForm.test.ts, src/components/hooks/useForm/useForm.ts, src/components/organisms/Form/Form/Form.test.tsx, src/components/organisms/Form/FormButton/FormButton.test.tsx, src/components/organisms/Form/FormDropdownField/FormDropdownField.test.tsx, src/components/organisms/Form/FormDropdownFilteredField/FormDropdownFilteredField.test.tsx, src/components/organisms/Form/FormTextField/FormTextField.test.tsx
Make it possible for the `validate` `<Form />` prop to be async
=> Make form validation async

package.json, styleguide.config.js, yarn.lock
fix it again since it breaks the styleguide (web)
=> fix(styleguide): fix react-scripts

src/components/organisms/Form/Form/Form.test.tsx, src/components/organisms/Form/FormButton/FormButton.test.tsx, src/components/organisms/Form/FormDropdownField/FormDropdownField.test.tsx, src/components/organisms/Form/FormDropdownFilteredField/FormDropdownFilteredField.test.tsx, src/components/organisms/Form/FormTextField/FormTextField.test.tsx, src/components/organisms/Form/hooks/useForm.test.ts, src/components/organisms/Form/hooks/useForm.ts
=> Form sync validation

src/components/organisms/Form/Form/Form.md, src/components/organisms/Form/Form/Form.test.tsx, src/components/organisms/Form/Form/Form.tsx, src/components/organisms/Form/FormButton/FormButton.md, src/components/organisms/Form/FormButton/FormButton.test.tsx, src/components/organisms/Form/FormCheckboxField/FormCheckboxField.md, src/components/organisms/Form/FormCheckboxField/FormCheckboxField.test.tsx, src/components/organisms/Form/FormDropdownField/FormDropdownField.md, src/components/organisms/Form/FormDropdownField/FormDropdownField.test.tsx, src/components/organisms/Form/FormDropdownFilteredField/FormDropdownFilteredField.md, src/components/organisms/Form/FormDropdownFilteredField/FormDropdownFilteredField.test.tsx, src/components/organisms/Form/FormRadioField/FormRadioField.md, src/components/organisms/Form/FormRadioField/FormRadioField.test.tsx, src/components/organisms/Form/FormTextField/FormTextField.md, src/components/organisms/Form/FormTextField/FormTextField.test.tsx, src/components/organisms/Form/index.md, src/components/organisms/Form/index.tsx
Split `<Form />` into `<Form />` component that holds the state and serves as a context provider, and `<Form.Form />` that grabs `handleSubmit` off of the context and passes it to the `<form />`'s `onSubmit`
=> Split form component

src/components/molecules/CheckboxField/CheckboxField.tsx, src/components/molecules/CheckboxGroupField/CheckboxGroupField.md, src/components/molecules/CheckboxGroupField/CheckboxGroupField.test.tsx, src/components/molecules/CheckboxGroupField/CheckboxGroupField.tsx, src/components/molecules/CheckboxGroupField/__snapshots__/CheckboxGroupField.test.tsx.snap, src/components/organisms/Form/FormCheckboxGroupField/FormCheckboxGroupField.md, src/components/organisms/Form/FormCheckboxGroupField/FormCheckboxGroupField.test.tsx, src/components/organisms/Form/FormCheckboxGroupField/FormCheckboxGroupField.tsx, src/components/organisms/Form/index.md, src/components/organisms/Form/index.tsx, src/index.ts
Add two components:
- `<CheckboxGroupField />`
- `<Form.CheckboxGroupField />`
=> Checkbox group field

src/components/atoms/Button/Button.md, src/components/atoms/Button/Button.tsx, src/components/atoms/Button/__snapshots__/Button.test.tsx.snap, src/components/atoms/Link/Link.md, src/components/atoms/Link/Link.tsx, src/index.ts
In order to facilitate usage with third party components, extract and export:
- `linkStyle`
- `buttonStyle`
=> Extract button and link styles

etc/docs/migration-v3.md, src/components/molecules/DropdownFiltered/DropdownFiltered.md, src/components/molecules/TextField/TextField.md
I missed couple of breaking changes on the migration guide. 💅🏻 💭
Thanks @poteirard for pointing them out 💯
=> Cleanup v3 documentation 

src/components/layout/FlexContainer/__snapshots__/FlexContainer.test.tsx.snap, src/components/layout/FlexRow/__snapshots__/FlexRow.test.tsx.snap, src/components/molecules/ZopaFooter/Links/__snapshots__/Links.test.tsx.snap, src/components/molecules/ZopaFooter/SocialLinks/__snapshots__/SocialLinks.test.tsx.snap, src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap, src/constants/grid.ts
I spoke to Rob and confirmed the container width and gutter size for the new designs
=> Update Flexible container size

src/components/molecules/Help/Help.tsx, src/components/molecules/Help/__snapshots__/Help.test.tsx.snap
Updating working hours due to COVID-19 situation.
=> fix(help): update opening hours

src/components/molecules/ZopaFooter/Links/Links.tsx, src/components/molecules/ZopaFooter/Links/__snapshots__/Links.test.tsx.snap, src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
only to be exposed after bank launch 🙇🏻‍♂️
=> Remove savings from Footer links 💸

package.json, src/components/atoms/Alert/Alert.md, src/components/atoms/Alert/Alert.test.tsx, src/components/atoms/Alert/Alert.tsx, src/components/atoms/Alert/__snapshots__/Alert.test.tsx.snap, src/components/atoms/AlertBox/AlertBox.md, src/components/atoms/AlertBox/AlertBox.tsx, src/components/atoms/README.md, src/index.ts, yarn.lock
https://jira.zopa/browse/ZDS-16
https://zopauk.github.io/react-components/#/Components/Atoms/Alert
=> feat(alert): create new Alert component and deprecate AlertBox

src/components/atoms/Alert/Alert.tsx, src/components/atoms/Alert/__snapshots__/Alert.test.tsx.snap
=> fix(alert): fix white space for svg

src/components/organisms/Accordion/AccordionHeader/AccordionHeader.tsx, src/components/organisms/Accordion/AccordionHeader/__snapshots__/AccordionHeader.test.tsx.snap
1. Do you guys are happy with the icons in CSS?
2. Do I have to remove the Arrow icon as it's not longer used?
Designs are not defined as 100% as I don't have a reference for the open state. Ask the design team is they are happy. I used this reference: https://marvelapp.com/e14bhc4/screen/67764982/handoff
Mine looks like this:
=> Add new Accordion designs

package.json
=> update version to v4.0.0--beta.5

src/components/organisms/Accordion/AccordionHeader/AccordionHeader.test.tsx, src/components/organisms/Accordion/AccordionHeader/AccordionHeader.tsx
Properly handle `onClick` prop in `<Accordion.Header />`
=> fix(accordionheader): fix onClick handler

src/components/molecules/DropdownFiltered/DropdownFiltered.tsx
Fix `disabled` state in `<DropdownFiltered />`
=> fix(dropdownfiltered): pass disabled to the text input

src/components/molecules/ZopaFooter/Links/Links.tsx, src/components/molecules/ZopaFooter/Links/__snapshots__/Links.test.tsx.snap, src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
Reset a footer link missed from the revert
=> fix(footer): change terms of use back to website terms

CHANGELOG.md, src/components/atoms/AlertBox/AlertBox.tsx, src/components/icons/Alert/Alert.tsx, src/components/icons/Arrow/Arrow.tsx, src/components/icons/CheckMark/CheckMark.tsx, src/components/icons/Chevron/Chevron.tsx, src/components/icons/Hamburger/Hamburger.tsx, src/components/icons/Profile/Profile.tsx, src/components/molecules/ZopaFooter/Links/Links.tsx, src/components/molecules/ZopaFooter/Links/__snapshots__/Links.test.tsx.snap, src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap, src/components/organisms/Accordion/AccordionHeader/AccordionHeader.test.tsx, src/components/organisms/Accordion/AccordionHeader/AccordionHeader.tsx
=> Get up to date with 'master' 🍉

etc/docs/migration-v4.md, src/README.md, src/components/atoms/Badge/Badge.md, src/components/atoms/Button/Button.tsx, src/components/atoms/Heading/Heading.md, src/components/atoms/Heading/Heading.test.tsx, src/components/atoms/Heading/Heading.tsx, src/components/atoms/Heading/__snapshots__/Heading.test.tsx.snap, src/components/atoms/Text/Text.md, src/components/atoms/Text/Text.test.tsx, src/components/atoms/Text/Text.tsx, src/components/molecules/Help/Help.tsx, src/components/molecules/Help/__snapshots__/Help.test.tsx.snap, src/components/molecules/ZopaFooter/Links/Links.tsx, src/components/molecules/ZopaFooter/Links/__snapshots__/Links.test.tsx.snap, src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
Removed the mb prop from `<Heading />`, `<Text />` & `<Badge />`
Update migration method and component documentation.
=> fix(spacing): remove mb prop and document atomic spacing classes

src/components/atoms/Link/Link.test.tsx, src/components/atoms/Link/Link.tsx, src/components/atoms/Link/__snapshots__/Link.test.tsx.snap
Allow the toggle of the target icon.
=> fix(link): toggle target icon

package.json
=> chore: new beta version

src/components/atoms/Button/Button.tsx, src/components/atoms/Button/__snapshots__/Button.test.tsx.snap, src/components/atoms/InputRange/InputRange.md, src/components/atoms/InputRange/InputRange.test.tsx, src/components/atoms/InputRange/InputRange.tsx, src/components/atoms/InputRange/__snapshots__/InputRange.test.tsx.snap, src/components/atoms/InputRange/styles/Button.tsx, src/components/atoms/InputRange/styles/Icon.tsx, src/components/atoms/InputRange/styles/Input.tsx, src/components/atoms/InputRange/styles/Wrapper.tsx, src/components/atoms/InputRange/styles/index.tsx
Adding controls to InputRange component.
https://priceless-poincare-18a246.netlify.app/#/Components/Atoms/InputRange
Related JIRA: https://jira.zopa/browse/SHOPDEV-6087
Notes:
- I also fixed the "focus" jump in the Buttons.
=> feat(inputrange): add controls option to InputRange

src/components/organisms/Card/CardContent/CardContent.tsx, src/components/organisms/Card/CardContent/__snapshots__/CardContent.test.tsx.snap
"Oh what an ass I am, you can tell it by my ears." - Shakespeare
=> fix(cardcontent): flex cardcontent

src/components/atoms/Badge/Badge.tsx, src/components/atoms/Badge/__snapshots__/Badge.test.tsx.snap
=> Rebrand <Badge />

CONTRIBUTING.md
=> Add documentation on how to do beta releases 🗒 🚀

CONTRIBUTING.md
I made some sections less verbose and hopefully now is easier to parse for new comers to this library 🙏🏻 ✍️ 🍜
=> Simplify CONTRIBUTING document

etc/semantic-release/config.js, package.json, yarn.lock
Upgrade semantic release and its plugins
Closes #236
=> Upgrade semantic release

src/components/atoms/Button/Button.tsx, src/components/atoms/Spinner/Spinner.tsx
This fixes some styling issues with SC v5
=> Fix incompatibility for sc v4

src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap, src/components/molecules/ZopaFooter/styles/Footer.tsx
=> fix(footer): fix typo

src/components/atoms/ErrorMessage/ErrorMessage.tsx, src/components/atoms/ErrorMessage/__snapshots__/ErrorMessage.test.tsx.snap, src/styleguide-components/Logo.js
=> Fix error messages

src/components/molecules/CheckboxField/CheckboxField.tsx, src/components/molecules/CheckboxField/__snapshots__/CheckboxField.test.tsx.snap
Unchecked disabled checkboxes should stay unchecked 👨‍🍳
=> fix(checkboxfield): fix disabled and checked style

src/components/atoms/ErrorMessage/ErrorMessage.tsx, src/components/atoms/ErrorMessage/__snapshots__/ErrorMessage.test.tsx.snap
=> refactor(errormessage): clean up styling

package.json
=> 4.0.0--beta.30

src/components/atoms/SidekickCard/__snapshots__/SidekickCard.test.tsx.snap, src/components/organisms/Navbar/Navbar/Navbar.md, src/components/organisms/Navbar/Navbar/Navbar.test.tsx, src/components/organisms/Navbar/Navbar/Navbar.tsx, src/components/organisms/Navbar/Navbar/__snapshots__/Navbar.test.tsx.snap, src/components/organisms/Navbar/NavbarAction/NavbarAction.tsx, src/components/organisms/Navbar/NavbarAction/__snapshots__/NavbarAction.test.tsx.snap, src/components/organisms/Navbar/NavbarDropdown/__snapshots__/NavbarDropdown.test.tsx.snap, src/components/organisms/Navbar/NavbarLink/NavbarLink.tsx, src/components/organisms/Navbar/NavbarLink/__snapshots__/NavbarLink.test.tsx.snap, src/components/organisms/Navbar/NavbarLinksList/__snapshots__/NavbarLinksList.test.tsx.snap, src/helpers/responsiveness.ts
Not the most elegant solution to [453](https://github.com/zopaUK/react-components/issues/453) but will avoid breaking changes for now.
Issues were:
- Content wasn't pushed down automatically
- When rendered at 1280px both text and icon wasn't displaying for `<Navbar.Action>`
=> Navbar fixes

etc/docs/migration-v4.md, src/components/molecules/Progress/Progress.md, src/components/molecules/Progress/Progress.test.tsx, src/components/molecules/Progress/Progress.tsx, src/components/molecules/Progress/__snapshots__/Progress.test.tsx.snap, tsconfig.json
=> Progress bar

src/components/atoms/Alert/Alert.md, src/components/atoms/Alert/Alert.tsx, src/components/atoms/Alert/__snapshots__/Alert.test.tsx.snap
I also fixed the hard-coded colors
=> feat(alert): add inline prop

src/components/molecules/ExpiryModal/ExpiryModal.tsx, src/components/organisms/Form/FormButton/FormButton.test.tsx
- fix types
- removed deprecated `wait`
=> Fix types expiry

src/components/atoms/Badge/Badge.md, src/components/atoms/Badge/Badge.test.tsx, src/components/atoms/Badge/Badge.tsx, src/components/atoms/Badge/__snapshots__/Badge.test.tsx.snap
- Fix styles
- Add brand style
https://jira.zopa/browse/ZDS-21
=> feat(badge): add brand styling and fix other styles

src/components/organisms/Navbar/Navbar/Navbar.md, src/components/organisms/Navbar/Navbar/__snapshots__/Navbar.test.tsx.snap, src/components/organisms/Navbar/NavbarDropdown/NavbarDropdown.tsx, src/components/organisms/Navbar/NavbarLinksList/NavbarLinksList.tsx, src/components/organisms/Navbar/NavbarLinksList/__snapshots__/NavbarLinksList.test.tsx.snap
Before (check Save link):
After:
=> fix(navbar): add separator for top single links

src/components/molecules/Progress/Progress.md, src/components/molecules/Progress/Progress.test.tsx, src/components/molecules/Progress/Progress.tsx, src/components/molecules/Progress/__snapshots__/Progress.test.tsx.snap
=> Fix progress edge states

src/components/atoms/Heading/Heading.md, src/components/atoms/Text/Text.md
Updated docs.
https://jira.zopa/browse/ZDS-26
=> docs(heading): update docs

src/components/atoms/InputLabel/InputLabel.tsx, src/components/atoms/InputLabel/__snapshots__/InputLabel.test.tsx.snap, src/components/molecules/CheckboxField/__snapshots__/CheckboxField.test.tsx.snap, src/components/molecules/DropdownField/__snapshots__/DropdownField.test.tsx.snap, src/components/molecules/DropdownFiltered/__snapshots__/DropdownFiltered.test.tsx.snap, src/components/molecules/RadioField/__snapshots__/RadioField.test.tsx.snap, src/components/molecules/TextField/__snapshots__/TextField.test.tsx.snap
Fix weight in InputLabel
https://jira.zopa/browse/ZDS-27
=> fix(label): fix weight

src/components/atoms/SidekickCard/SidekickCard.test.tsx, src/components/atoms/SidekickCard/SidekickCard.tsx, src/components/molecules/RadioField/RadioField.test.tsx, src/components/molecules/RadioField/RadioField.tsx
Add deprecation warnings for RadioField and SidekickCard
https://jira.zopa/browse/ZDS-35
=> Add warnings for RadioField and SidekickCard

src/components/organisms/Navbar/Navbar/Navbar.tsx, src/components/organisms/Navbar/NavbarLinksList/NavbarLinksList.tsx
Fix to solve this => https://jira.zopa/browse/SHOPDEV-7585
=> fix(navbar): close navbar dropdown on link click

src/components/layout/README.md
=> chore(layout): fix layout links for PROD

src/components/atoms/InputText/InputText.tsx
=> fix(inputtext): add missing semicolon

src/components/organisms/Accordion/AccordionHeader/AccordionHeader.tsx, src/components/organisms/Accordion/AccordionHeader/__snapshots__/AccordionHeader.test.tsx.snap
=> Fix accordion opener

src/components/molecules/CheckboxField/CheckboxField.tsx, src/components/molecules/CheckboxField/__snapshots__/CheckboxField.test.tsx.snap, src/components/molecules/RadioField/RadioField.tsx
Add box shadow to checkbox and radio's hover state
=> Tweak checkbox and radio hover state

src/components/organisms/Card/index.tsx
=> fix(card): extend Card interface to be able to use html props

.circleci/config.yml, package.json, yarn.lock
- Dowgrade react/types
- Upgrade font-awesome packageswith the fixes in types
- Add typecheck in ci tasks
=> chore(typechecking): fix type errors and typecheck in ci

src/components/molecules/CheckboxGroupField/CheckboxGroupField.md, src/components/molecules/CheckboxGroupField/CheckboxGroupField.tsx, src/components/molecules/CheckboxGroupField/__snapshots__/CheckboxGroupField.test.tsx.snap, src/components/molecules/RadioGroupField/RadioGroupField.md, src/components/molecules/RadioGroupField/RadioGroupField.tsx, src/components/molecules/RadioGroupField/__snapshots__/RadioGroupField.test.tsx.snap
Make the following components responsive
- `<RadioGroupField />`
- `<CheckboxGroupField />`
=> Make group field components responsive

src/components/molecules/RadioField/RadioField.tsx, src/components/molecules/RadioGroupField/RadioGroupField.md, src/components/molecules/RadioGroupField/RadioGroupField.tsx, src/components/types.ts
Add optional loading icon to radiofield when selected and make label optional
=> feat(radiofield): add optional loading icon when selected

src/components/molecules/CheckboxField/CheckboxField.md, src/components/molecules/CheckboxField/CheckboxField.test.tsx, src/components/molecules/CheckboxField/CheckboxField.tsx, src/components/molecules/CheckboxField/__snapshots__/CheckboxField.test.tsx.snap, src/components/molecules/CheckboxGroupField/CheckboxGroupField.md, src/components/molecules/CheckboxGroupField/CheckboxGroupField.test.tsx, src/components/molecules/CheckboxGroupField/CheckboxGroupField.tsx, src/components/molecules/CheckboxGroupField/__snapshots__/CheckboxGroupField.test.tsx.snap, src/components/molecules/RadioField/RadioField.md, src/components/molecules/RadioField/RadioField.test.tsx, src/components/molecules/RadioField/RadioField.tsx, src/components/molecules/RadioGroupField/RadioGroupField.md, src/components/molecules/RadioGroupField/RadioGroupField.test.tsx, src/components/molecules/RadioGroupField/RadioGroupField.tsx, src/components/molecules/RadioGroupField/__snapshots__/RadioGroupField.test.tsx.snap, src/components/organisms/Form/FormRadioGroupField/FormRadioGroupField.tsx, src/components/types.ts
Add prop to hide the icon on the following components: 
- `<RadioGroupField />`
- `<CheckboxGroupField />`
Update selected state
=> Radio/checkbox show/hide icon

src/components/atoms/Legend/Legend.tsx, src/components/atoms/Legend/__snapshots__/Legend.test.tsx.snap, src/components/atoms/Text/Text.tsx, src/components/molecules/CheckboxGroupField/CheckboxGroupField.tsx, src/components/molecules/CheckboxGroupField/__snapshots__/CheckboxGroupField.test.tsx.snap, src/components/molecules/RadioGroupField/RadioGroupField.tsx, src/components/molecules/RadioGroupField/__snapshots__/RadioGroupField.test.tsx.snap
+ added semi bold font styling to the Legend element
+ fixed padding to use sizing classes
=> fix(legend): fixes some spacing and font weight issues with Legend

src/components/atoms/Legend/Legend.tsx, src/components/atoms/Legend/__snapshots__/Legend.test.tsx.snap, src/components/molecules/CheckboxGroupField/__snapshots__/CheckboxGroupField.test.tsx.snap, src/components/molecules/RadioGroupField/__snapshots__/RadioGroupField.test.tsx.snap
+ fix the incorrect use of the "semi-bold" keyword and add some basic text styles to the Legend component.
=> fix(legend): fixes incorrect semi-bold font weight css keyword

src/components/atoms/Text/Text.tsx, src/components/organisms/Form/FormSection/FormSection.md, src/components/organisms/Form/FormSection/FormSection.test.tsx, src/components/organisms/Form/FormSection/FormSection.tsx, src/components/organisms/Form/FormSection/__snapshots__/FormSection.test.tsx.snap, src/components/organisms/Form/index.ts
A component to group a set of inputs in a form. Will handle consistent spacing between all inputs and can add a title and/or subtitle
=> Form Section component

src/components/atoms/Text/Text.md, src/components/atoms/Text/Text.test.tsx, src/components/atoms/Text/Text.tsx, src/components/organisms/Form/FormSection/__snapshots__/FormSection.test.tsx.snap
To support then design system more - adding semi bold to the font weights allowed by the Text component.
=> feat(text): adds semibold to the public api for Text

package.json, src/components/atoms/Alert/Alert.tsx, src/components/atoms/Alert/__snapshots__/Alert.test.tsx.snap, src/components/molecules/Banner/Banner.md, src/components/molecules/Banner/Banner.test.tsx, src/components/molecules/Banner/Banner.tsx, src/components/molecules/Banner/__snapshots__/Banner.test.tsx.snap, src/components/molecules/Notification/Notification.md, src/components/molecules/Notification/Notification.test.tsx, src/components/molecules/Notification/Notification.tsx, src/components/molecules/Notification/__snapshots__/Notification.test.tsx.snap, yarn.lock
encapsulates domain naming of "Banner" and "Notification" and handles the visual differences (rounded corners)
=> feat(alert): adds banner and notification components

src/components/atoms/Alert/Alert.tsx, src/components/atoms/InputText/InputText.test.tsx, src/components/atoms/InputText/__snapshots__/InputText.test.tsx.snap, src/components/molecules/Modal/Modal.test.tsx, src/components/molecules/Modal/Modal.tsx, src/components/molecules/Modal/__snapshots__/Modal.test.tsx.snap, src/components/organisms/Accordion/AccordionHeader/AccordionHeader.test.tsx, src/components/organisms/Accordion/AccordionHeader/__snapshots__/AccordionHeader.test.tsx.snap, src/components/organisms/Accordion/AccordionSection/AccordionSection.test.tsx, src/components/organisms/Accordion/AccordionSection/__snapshots__/AccordionSection.test.tsx.snap, src/components/organisms/Card/CardImage/CardImage.test.tsx, src/components/organisms/Form/FormCheckboxField/FormCheckboxField.test.tsx, src/components/organisms/Form/FormCheckboxGroupField/FormCheckboxGroupField.test.tsx, src/components/organisms/Form/FormDropdownField/FormDropdownField.test.tsx, src/components/organisms/Form/FormDropdownFilteredField/FormDropdownFilteredField.test.tsx, src/components/organisms/Form/FormRadioGroupField/FormRadioGroupField.test.tsx, src/components/organisms/Form/FormTextField/FormTextField.test.tsx, src/components/organisms/Navbar/Navbar/Navbar.tsx, src/components/organisms/Navbar/Navbar/__snapshots__/Navbar.test.tsx.snap, src/setupTests.ts
replace data-testid with data-automation
=> test(data testid): replace data-testid with data-automation

src/index.ts
Make sure Notification and Banner are exported
=> fix(notification): adds export of notification and banner

.circleci/config.yml, package.json, yarn.lock
- Deploy to Netlify (also deploy previews)
=> chore(web): deploy with netlify instead of gh-pages

src/components/molecules/NumberText/NumberText.md, src/components/molecules/NumberText/NumberText.test.tsx, src/components/molecules/NumberText/NumberText.tsx
Add fallback option to NumberText
=> feat(number text): add fallback option

src/components/molecules/Help/__snapshots__/Help.test.tsx.snap, src/components/organisms/Card/Card/Card.tsx, src/components/organisms/Card/Card/__snapshots__/Card.test.tsx.snap, src/components/organisms/Card/CardHeading/__snapshots__/CardHeading.test.tsx.snap, src/components/organisms/Card/CardImage/__snapshots__/CardImage.test.tsx.snap, src/components/organisms/Card/CardLineItem/CardLineItem.md, src/components/organisms/Card/CardLineItem/CardLineItem.test.tsx, src/components/organisms/Card/CardLineItem/CardLineItem.tsx, src/components/organisms/Card/CardLineItem/__snapshots__/CardLineItem.test.tsx.snap, src/components/organisms/Card/CardText/__snapshots__/CardText.test.tsx.snap, src/components/organisms/Card/README.md, src/components/organisms/Card/index.tsx
Adds the `action` prop to `<Card />` and `<CardLineItem />` that can be used together to create an 'action' card
=> Card line item

src/components/molecules/NumberText/NumberText.md, src/components/molecules/NumberText/NumberText.test.tsx, src/components/molecules/NumberText/NumberText.tsx, src/components/molecules/NumberText/__snapshots__/NumberText.test.tsx.snap
Add an additional font size
Add ability to control title font size
Add text align prop
Add semiBold prop
=> Update number text

src/components/templates/ProductTemplate/ProductTemplate/ProductTemplate.test.tsx, src/components/templates/ProductTemplate/ProductTemplate/ProductTemplate.tsx, src/components/templates/ProductTemplate/ProductTemplate/__snapshots__/ProductTemplate.test.tsx.snap
Wrap the content of the template in a container to set the width of the content and center it.
=> Zds 41 add container to template

src/components/templates/ProductTemplate/ProductTemplate/ProductTemplate.tsx, src/components/templates/ProductTemplate/ProductTemplate/__snapshots__/ProductTemplate.test.tsx.snap, src/components/templates/ProductTemplate/ProductTemplateHeader/__snapshots__/ProductTemplateHeader.test.tsx.snap, src/components/templates/ProductTemplate/ProductTemplateNavigation/ProductTemplateNavigation.tsx, src/components/templates/ProductTemplate/ProductTemplateNavigation/__snapshots__/ProductTemplateNavigation.test.tsx.snap, src/components/templates/ProductTemplate/ProductTemplateTitle/ProductTemplateTitle.tsx, src/components/templates/ProductTemplate/ProductTemplateTitle/__snapshots__/ProductTemplateTitle.test.tsx.snap
- Fix alignment back button progress bar
- Fix size and colour chevron icon
- Fix top margin product template
- Fix margin title
Designs: https://www.sketch.com/s/f792aa60-01d9-472d-b53c-c74dd501ef9c/a/E0land
=> Product template: fix styles back button and margins

src/components/molecules/NumberText/NumberText.test.tsx, src/components/molecules/NumberText/NumberText.tsx
Handle negative numbers in `<NumberText />` component. If a negative number is passed, it should be displayed
=> fix(number text): handle negative numbers

src/components/atoms/Icon/Icon.tsx
=> feat(icon): Update Icon.tsx

src/components/molecules/NumberText/NumberText.tsx
Make it possible to set the className to the title.
=> fix(numbertext): add titleClassName prop

src/modules.d.ts
=> fix(typings): add gif to module typings

src/components/atoms/Dropdown/Dropdown.tsx, src/components/atoms/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/components/atoms/InputText/InputText.tsx, src/components/atoms/InputText/__snapshots__/InputText.test.tsx.snap, src/components/molecules/DropdownFiltered/__snapshots__/DropdownFiltered.test.tsx.snap, src/components/molecules/TextField/__snapshots__/TextField.test.tsx.snap, src/components/organisms/Tabs/TabButtons/__snapshots__/TabButtons.test.tsx.snap
https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone
=> fix(inputs): bug with iphone safari

package.json
Apparently it runs in the consumer of the app too
=> fix(pnpm): unforce pnpm

src/components/templates/ProductTemplate/ProductTemplate/ProductTemplate.test.tsx, src/components/templates/ProductTemplate/ProductTemplate/ProductTemplate.tsx, src/components/templates/ProductTemplate/ProductTemplate/__snapshots__/ProductTemplate.test.tsx.snap, src/components/templates/ProductTemplate/ProductTemplateHeader/ProductTemplateHeader.test.tsx, src/components/templates/ProductTemplate/ProductTemplateHeader/ProductTemplateHeader.tsx, src/components/templates/ProductTemplate/ProductTemplateHeader/__snapshots__/ProductTemplateHeader.test.tsx.snap, src/components/templates/ProductTemplate/ProductTemplateNavigation/ProductTemplateNavigation.test.tsx, src/components/templates/ProductTemplate/ProductTemplateNavigation/ProductTemplateNavigation.tsx, src/components/templates/ProductTemplate/README.md
#637 
Optional `onBackPressed` callback property on back button click
=> feat(producttemplate): onBackPressed callback

src/components/organisms/Card/CardImage/CardImage.tsx
Add missing semicolon to `<Card.Image>` css
=> fix(card): add missing semicolon to css

src/components/molecules/Help/Help.tsx, src/components/molecules/Help/__snapshots__/Help.test.tsx.snap, src/components/templates/ErrorPages/Maintenance/Maintenance.tsx, src/components/templates/ErrorPages/Maintenance/__snapshots__/Maintenance.test.tsx.snap, src/index.ts
Updates to Help component to correctly display contact and general information for both borrowers and investors. Changes also made to Maintenance in order for this component to continue to work as expected.
=> Investor help component

src/components/atoms/List/Item/Item.tsx, src/components/atoms/List/Item/__snapshots__/Item.test.tsx.snap, src/components/atoms/List/List/__snapshots__/List.test.tsx.snap
Fix small issue with adding classnames to list items
=> Update List Item component

src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap, src/components/molecules/ZopaFooter/styles/SocialLink.tsx
open social links in the footer in a new tab
=> fix(footer): update social links

src/components/molecules/Modal/Modal.tsx
- move onClick handler from icon to button
- add z-index to the button higher than the default z-index of the overlay
=> Modal Close button fix

src/components/molecules/ZopaFooter/ZopaFooter.tsx, src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
Adding Complaints button leading to /contact/complaints under the About Zopa section in the ZopaFooter component
=> feat(zopafooter.tsx): Adding Complaints button to ZopaFooter component

src/components/molecules/LoadingSection/LoadingSection.md, src/components/molecules/LoadingSection/LoadingSection.test.tsx, src/components/molecules/LoadingSection/LoadingSection.tsx, src/components/organisms/Tabs/TabButtons/__snapshots__/TabButtons.test.tsx.snap, src/components/organisms/Tabs/TabsContainer/__snapshots__/TabsContainer.test.tsx.snap, src/index.ts
Create component Loading Section which contains:
- spinner
- primary text
- secondary text
=> Add new LoadingSection component

src/components/organisms/Navbar/Navbar/__snapshots__/Navbar.test.tsx.snap, src/components/organisms/Navbar/NavbarDropdown/NavbarDropdown.test.tsx, src/components/organisms/Navbar/NavbarDropdown/NavbarDropdown.tsx, src/components/organisms/Navbar/NavbarDropdown/NavbarDropdownList/NavbarDropdownList.test.tsx, src/components/organisms/Navbar/NavbarDropdown/NavbarDropdownList/NavbarDropdownList.tsx, src/components/organisms/Navbar/NavbarDropdown/NavbarDropdownList/__snapshots__/NavbarDropdownList.test.tsx.snap, src/components/organisms/Navbar/NavbarDropdown/__snapshots__/NavbarDropdown.test.tsx.snap, src/components/organisms/Navbar/NavbarLinksList/__snapshots__/NavbarLinksList.test.tsx.snap, src/components/organisms/Tabs/TabButtons/__snapshots__/TabButtons.test.tsx.snap, src/components/organisms/Tabs/TabsContainer/__snapshots__/TabsContainer.test.tsx.snap
Will fix https://github.com/zopaUK/react-components/issues/683
Also adds axe tests to the navbar dropdown component
=> fix(navbar): remove ul that's a direct child of a ul

src/components/templates/ProductTemplate/ProductTemplate/ProductTemplate.test.tsx, src/components/templates/ProductTemplate/ProductTemplate/ProductTemplate.tsx, src/components/templates/ProductTemplate/ProductTemplateHeader/ProductTemplateHeader.tsx, src/components/templates/ProductTemplate/ProductTemplateHeader/__snapshots__/ProductTemplateHeader.test.tsx.snap
Should fix https://github.com/zopaUK/react-components/issues/685
=> fix(producttemplate): add <main> landmark to the product template

pnpm-lock.yaml, src/components/templates/ProductTemplate/ProductTemplate/ProductTemplate.tsx
The main tag should be defined by the developer using this component not inside this component.
The main landmark should be defined much higher up the dom tree.
=> fix(landmarks): remove main landmark from product template

src/components/organisms/Navbar/Navbar/Navbar.tsx, src/components/organisms/Navbar/Navbar/__snapshots__/Navbar.test.tsx.snap, src/components/organisms/Tabs/TabButtons/__snapshots__/TabButtons.test.tsx.snap, src/components/organisms/Tabs/TabsContainer/__snapshots__/TabsContainer.test.tsx.snap
A tiny fix for https://github.com/zopaUK/react-components/issues/705.
When `NavbarAction` is rendered within list, it should be wrapped in `<li>`
=> Fix navbar CTA 

src/components/molecules/TextField/TextField.test.tsx, src/components/organisms/Carousel/CarouselSlide/CarouselSlide.test.tsx, src/components/organisms/Carousel/CarouselSlide/__snapshots__/CarouselSlide.test.tsx.snap, src/components/organisms/Tabs/TabButton/TabButton.tsx, src/components/organisms/Tabs/TabButton/__snapshots__/TabButton.test.tsx.snap, src/components/organisms/Tabs/TabButtons/__snapshots__/TabButtons.test.tsx.snap, src/components/organisms/Tabs/TabContent/TabContent.tsx, src/components/organisms/Tabs/TabsContainer/__snapshots__/TabsContainer.test.tsx.snap, src/components/templates/ProductTemplate/ProductTemplateHeader/ProductTemplateHeader.test.tsx, src/components/templates/ProductTemplate/ProductTemplateHeader/__snapshots__/ProductTemplateHeader.test.tsx.snap
=> fix(warnings): fix warnings in components

src/components/atoms/Alert/Alert.tsx, src/components/atoms/Alert/__snapshots__/Alert.test.tsx.snap, src/components/molecules/BankDetails/BankDetails.tsx, src/components/molecules/BankDetails/__snapshots__/BankDetails.test.tsx.snap, src/components/molecules/Banner/__snapshots__/Banner.test.tsx.snap, src/components/molecules/Notification/__snapshots__/Notification.test.tsx.snap
The bank details component should have 16px from the RHS.
The alert's spacing is incorrect.
=> Design Amends to the Alert & Bank Details components

src/content/Helpers/Helpers.md, src/content/Helpers/Helpers.tsx
=> feat(documentation): add helpers for responsive functions

src/components/molecules/ZopaFooter/ZopaFooter.tsx, src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
=> fix(footer): update typo

src/components/molecules/ZopaFooter/ZopaFooter.tsx, src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
Add Press Office link under About Zopa to https://www.zopa.com/about/press
https://jira.zopa/browse/SHOPDEV-8824
=> Add Press Office to ZopaFooter

src/components/molecules/ZopaFooter/ZopaFooter.tsx, src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
Change button copy from Press Office -> Press office
=> fix(zopafooter): copy change to press office button

src/components/molecules/ZopaFooter/ZopaFooter.test.tsx, src/components/molecules/ZopaFooter/ZopaFooter.tsx, src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
added link for car hire purchase
=> feat(zopafooter): adding link for car hire purchase

src/components/molecules/ZopaFooter/ZopaFooter.tsx, src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
=> feat(zopafooter): adding remuneration link

src/components/molecules/ZopaFooter/ZopaFooter.tsx, src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
=> feat: add smart saver to footer

src/components/atoms/RoundButton/RoundButton.md, src/components/atoms/RoundButton/RoundButton.test.tsx, src/components/atoms/RoundButton/RoundButton.tsx, src/components/atoms/RoundButton/__snapshots__/RoundButton.test.tsx.snap, src/index.ts
We need to build a round button component as part of Zopa's upcoming projects:
=> feat: round button component

src/components/atoms/RoundButton/RoundButton.tsx, src/components/atoms/RoundButton/__snapshots__/RoundButton.test.tsx.snap
=> fix-round-button-style

src/components/atoms/RoundButton/RoundButton.md, src/components/atoms/RoundButton/RoundButton.test.tsx, src/components/atoms/RoundButton/RoundButton.tsx, src/components/atoms/RoundButton/__snapshots__/RoundButton.test.tsx.snap
=> Update round buttons

src/components/atoms/RoundButton/RoundButton.tsx
=> Include as ts prop

src/components/molecules/Help/__snapshots__/Help.test.tsx.snap, src/components/organisms/Card/Card/Card.test.tsx, src/components/organisms/Card/Card/Card.tsx, src/components/organisms/Card/Card/__snapshots__/Card.test.tsx.snap, src/components/organisms/Card/CardHeading/__snapshots__/CardHeading.test.tsx.snap, src/components/organisms/Card/CardImage/__snapshots__/CardImage.test.tsx.snap, src/components/organisms/Card/CardLineItem/CardLineItem.tsx, src/components/organisms/Card/CardLineItem/__snapshots__/CardLineItem.test.tsx.snap, src/components/organisms/Card/CardText/__snapshots__/CardText.test.tsx.snap, src/components/organisms/Card/README.md, src/components/templates/ProductTemplate/ProductTemplateCard/__snapshots__/ProductTemplateCard.test.tsx.snap
https://jira.zopa/browse/ZUI-11
=> feat(new styling to card): new 'info' style for Card

src/components/molecules/CheckboxField/CheckboxField.tsx, src/components/molecules/DropdownFiltered/Option.ts, src/components/molecules/DropdownFiltered/Options.ts, src/components/styles/Theme.tsx, src/content/images/jl-tick.svg
Add theme to CheckBoxField
Add new properties to theme.input.checkBox
=> Add theme to CheckBox

src/components/atoms/ScrollableArea/ScrollableArea.tsx, src/components/styles/Theme.tsx
- refactored to functional component to be able to access theme context
- `scrollBarTrack` background color, border-radius are themeable
- `scrollBarThumb`  background color, border-radius and border are themeable
=> Add theming to ScrollableArea

src/components/atoms/ScrollableArea/ScrollableArea.tsx
- fix missing `forwardRef` in ScrollableArea
=> fix(scrollablearea): fix missing ref

src/components/atoms/ScrollableArea/ScrollableArea.tsx
removing unecessary type declarataion
=> fix(scrollablearea): type fix

src/components/styles/Theme.tsx, src/components/templates/ProductTemplate/ProductTemplateTitle/ProductTemplateTitle.tsx, src/components/templates/ProductTemplate/ProductTemplateTitle/__snapshots__/ProductTemplateTitle.test.tsx.snap
Allow product template to be customisable:
=> Add theme to product template title

src/components/atoms/Button/Button.tsx, src/components/atoms/Button/__snapshots__/Button.test.tsx.snap, src/components/atoms/Text/Text.tsx, src/components/molecules/BankDetails/__snapshots__/BankDetails.test.tsx.snap, src/components/molecules/Help/__snapshots__/Help.test.tsx.snap, src/components/organisms/Navbar/Navbar/__snapshots__/Navbar.test.tsx.snap, src/components/organisms/Navbar/NavbarAction/__snapshots__/NavbarAction.test.tsx.snap, src/components/organisms/Tabs/TabButton/__snapshots__/TabButton.test.tsx.snap, src/components/organisms/Tabs/TabButtons/__snapshots__/TabButtons.test.tsx.snap, src/components/organisms/Tabs/TabsContainer/__snapshots__/TabsContainer.test.tsx.snap, src/components/styles/Theme.tsx, src/components/templates/ErrorPages/FiveHundred/__snapshots__/FiveHundred.test.tsx.snap, src/components/templates/ErrorPages/Four0Four/__snapshots__/Four0Four.test.tsx.snap
- add theming for letter-spacing to `Text` and `Button` components
=> fix(text): add theming for letter spacing to text and button

src/components/atoms/InputLabel/InputLabel.tsx, src/components/styles/Theme.tsx
Allow theme to set margin for Label
=> feat(label): make label margin themable

src/components/molecules/ZopaFooter/ZopaFooter.tsx
Add the ability to add partner info to footer
=> feat: add partner info to footer

src/components/atoms/Spinner/CustomSpinner/CustomSpinner.tsx
- fixing typos in `CustomSpinner`
=> fix(spinner): fixing typos in customspinner

src/components/molecules/ZopaFooter/ZopaFooter.tsx, src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
- adding link for Annual Reports and Pillar 3 (`/investor-information`)
=> Update footer 

.github/workflows/contributors.yaml, README.md
https://github.com/akhilmhdh/contributors-readme-action
=> ci(contributors): add contributors github action

pnpm-lock.yaml, src/components/styles/Theme/Theme.md, src/components/styles/Theme/ThemeProvider.md, src/components/styles/Theme/ThemeProvider.tsx, src/components/styles/Theme/index.tsx, styleguide.config.js
=> feat: add documentation for ThemeProvider component

.github/workflows/ci.yaml, .gitignore, etc/netlify/netlify.sh, netlify.toml, package.json, pnpm-lock.yaml
Switching to pnpm7 to use the latest features.
=> chore(pnpm): migrate to pnpm 7 lockfile + 7.15.0

package.json, pnpm-lock.yaml
Upgrading styleguidist to the latest version.
See: https://react-styleguidist.js.org/
=> chore(styleguidist): upgrade styleguidist to 13

pnpm-lock.yaml, src/components/atoms/InputText/InputText.tsx, src/components/atoms/InputText/__snapshots__/InputText.test.tsx.snap, src/components/molecules/DropdownFiltered/__snapshots__/DropdownFiltered.test.tsx.snap, src/components/molecules/TextField/__snapshots__/TextField.test.tsx.snap, src/components/types.ts
there was no ability to adjust font size or weight in the inputtext atom so i've added those props in so that for future components we can amend the size and weight as per design needs. the default remains the same so should have no impact on other uses on inputtext, but the option to adjust font size and weight from the default will now be there
=> Uplfe1031b

etc/rollup/config.mjs, package.json, pnpm-lock.yaml
- feat(bundle): switch babel out for swc
- build(deps): install dependencies
=> Swap to using swc instead of babel

README.md, src/components/atoms/Trustpilot/Stars/Stars.tsx, src/components/atoms/Trustpilot/Stars/__snapshots__/Stars.test.tsx.snap, src/components/atoms/Trustpilot/__snapshots__/Trustpilot.test.tsx.snap
Changest trustpilot svg title to be dynamically set according to the rating:
https://jira.zopa/browse/ZUI-75
=> ZUI 75 trustpilot title

CONTRIBUTING.md
=> docs(contributing): switch yarn to pnpm

src/components/organisms/Accordion/AccordionHeader/AccordionHeader.tsx
Jira ticket
https://jira.zopa/browse/ZUI-13
=> style: fixed Accordion icon position

src/components/atoms/Button/Button.md, src/components/atoms/Icon/Icon.md, src/components/atoms/Icon/Icon.tsx, src/components/molecules/DropdownFiltered/__snapshots__/DropdownFiltered.test.tsx.snap
=> Added ariaLabel for Icon

src/components/molecules/ZopaFooter/ZopaFooter.test.tsx, src/components/molecules/ZopaFooter/ZopaFooter.tsx, src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
Update the footer to include two new links and update existing one:
Car finance - /car-finance
Hire purchase (HP) - /car-finance/hp
Personal contract purchase (PCP) - /car-finance/pcp
=> feat(footer): update footer links

src/components/atoms/InputRange/InputRange.md, src/components/atoms/InputRange/InputRange.tsx
=> fix(inputrange): add id to input range

src/components/atoms/Alert/Alert.tsx, src/components/atoms/Alert/__snapshots__/Alert.test.tsx.snap, src/components/molecules/Banner/__snapshots__/Banner.test.tsx.snap, src/components/molecules/Notification/__snapshots__/Notification.test.tsx.snap
Add role=status to Alert to be accessible as per audit
=> Role status

CODEOWNERS
Remove these two from codeowners
=> chore(codeowners): remove codeowners

src/components/templates/ProductTemplate/ProductTemplateTitle/ProductTemplateTitle.tsx, src/components/templates/ProductTemplate/ProductTemplateTitle/__snapshots__/ProductTemplateTitle.test.tsx.snap
=> Product template title spacing

.changeset/few-timers-pump.md, src/components/atoms/InputText/InputText.md, src/components/atoms/InputText/InputText.tsx, src/components/atoms/InputText/__snapshots__/InputText.test.tsx.snap, src/components/molecules/CheckboxField/CheckboxField.md, src/components/molecules/RadioField/RadioField.md, src/components/molecules/RadioGroupField/RadioGroupField.md, src/components/molecules/TextField/__snapshots__/TextField.test.tsx.snap
Fix valid and error state border colours
=> Fix: text input borders

.changeset/chatty-stingrays-pretend.md, src/components/atoms/ConditionalWrapper/ConditionalWrapper.test.tsx, src/components/atoms/ConditionalWrapper/ConditionalWrapper.tsx, src/components/organisms/Navbar/Navbar/Navbar.tsx, src/components/styles/Theme/ThemeProvider.tsx, tsconfig.json
The theme properties for the Navbar component have been updated to
better support responsive design. The 'desktop' and 'medium' properties
have been renamed to 'desktopMinMedia' and 'desktopMaxMedia' respectively.
This change will allow for more precise styling at different viewport sizes.
=> Navbar updates

.changeset/shaggy-bears-dance.md, tsconfig.json
Reverting the tsconfig jsx to react
=> feat: tsconfig jsx to react

.changeset/angry-poets-teach.md, src/components/atoms/Alert/Alert.tsx
https://jira.zopa/browse/OBAU-25949
=> Alert V2 - more refactoring 

src/components/atoms/Heading/Heading.tsx, src/components/atoms/InputLabel/InputLabel.tsx, src/components/atoms/InputText/InputText.tsx, src/components/atoms/Legend/Legend.tsx, src/components/molecules/DropdownFiltered/Option.ts, src/components/molecules/RadioGroupField/RadioGroupField.tsx, src/components/styles/Theme/ThemeProvider.tsx, src/components/templates/ProductTemplate/ProductTemplateTitle/ProductTemplateTitle.tsx, src/components/types.ts
https://jira.zopa/browse/OBAU-26623
=> Fonts alignment

.changeset/fifty-schools-grin.md, src/components/molecules/ZopaFooter/ZopaFooter.tsx, src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
https://jira.zopa/browse/WEBP-1807
=> WEBP-1807: add tax strategy pdf

.changeset/selfish-horses-check.md
=> WEBP-1807/fix(footer): redo changeset

.changeset/warm-wasps-occur.md, src/components/layout/FlexContainer/FlexContainer.tsx, src/components/styles/Theme/ThemeProvider.tsx, src/components/templates/ProductTemplate/ProductTemplate/ProductTemplateV2.tsx
Adding a new ability to theme the application - passing a utility classname will allow third party applications to control the theme.
The library has `FlexContainer` which contains various zopaisms.
This lets us override it.
=> feat: support more classnames

.changeset/ten-waves-camp.md, src/components/molecules/CheckboxField/CheckboxField.tsx, src/components/molecules/CheckboxField/__snapshots__/CheckboxField.test.tsx.snap, src/components/molecules/CheckboxGroupField/__snapshots__/CheckboxGroupField.test.tsx.snap, src/components/styles/Theme/ThemeProvider.tsx, src/content/images/unbranded-tick-white.svg
Support background color
Custom icon
=> Checkbox theme v2

.changeset/lemon-fireants-exercise.md, src/components/templates/ProductTemplate/ProductTemplate/ProductTemplateV2.tsx
Add the ability to control the styles applied in the product-template-row
=> feat: use classnames to control styling in template

.changeset/gentle-islands-jump.md, src/components/templates/ProductTemplate/ProductTemplate/ProductTemplateV2.tsx
Make the template more flexible
=> Refactor template to be more flexible

.changeset/red-sloths-matter.md
- **fix: refactor product-template**
- **chore: changeset**
- **chore: changeset**
=> Release the change

.changeset/cyan-eyes-rest.md, src/components/organisms/Navbar/Navbar/NavbarLite.tsx, src/components/organisms/NavbarLite/NavbarLite.tsx, src/components/styles/Theme/ThemeProvider.tsx, src/components/templates/ProductTemplate/ProductTemplate/ProductTemplateV2.tsx, src/index.ts
- **feat: update @types/react to latest**
- **chore: update the test tooling**
- **chore: remove reference to NavbarLite**
- **chore: use legacyRoot for Stars.tsx**
- **chore: changeset**
- **chore: pnpm lockfile**
- **feat: add NabarLite**
=> cobranded nav

.changeset/chilled-birds-smile.md, src/components/molecules/ZopaFooter/ZopaFooter.tsx, src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
=> feat: zopa footer accept cobranding
