- src/components/atoms/InputText/InputText.tsx
- src/components/atoms/Link/Link.tsx
- src/components/molecules/RadioField/RadioField.tsx
- src/components/organisms/Accordion/AccordionSection/AccordionSection.tsx
- src/components/organisms/Navbar/NavbarLink/NavbarLink.tsx
- src/helpers/utils.ts
Website is showing strange names instead of the components.
There where some types which weren't parsed properly by react-styleguidist. These are some patches done to make it work properly. Also `getBorderColorByStatus` has been moved to `helpers/utils` as it's a better place for something that generic.
> fix(website): fix types forwardRefs and function

- .circleci/config.yml
- package.json
- yarn.lock
Now we can see metadata for the failing tests and lint errors in Circle CI:
info from the tests in the circle ci
> ci(circleci): add tests reports

- src/components/styles/Fonts.tsx
Google Fonts is [finally supporting `font-display: swap`](https://www.zachleat.com/web/google-fonts-display/).
We recently added this strategy for the _"display"_ font, **Alvereta**, and to be consistent I recommend we add it too for the _"text"_ font, **Open Sans**. 
During the time it takes **Open Sans** to load, the browser will display a [system font stack](https://github.com/zopaUK/react-components/blob/master/src/constants/fonts.ts#L2).
This strategy brings benefits in page load performance on _slow networks_ ( as suggested by [Google Lighthouse](https://developers.google.com/web/tools/lighthouse/) ), as the browser doesn't need to paint invisible text and the content is available straight away once the user lands on the page.
> Enable `font-display: swap` for Open Sans

- src/styleguide-components/README.md
- src/styleguide-components/Table.js
- styleguide.config.js
> fix(styleguide): fix column space of props & methods

- src/components/icons/Hamburger/Hamburger.md
Following #31, I imported `<HamburgerIcon />` wrongly on its example 👍🏻
> Fix <HamburgerIcon /> example 

- src/content/Colors/Colors.md
- src/content/Colors/Colors.tsx
Basically, I removed all the marked parts to make things less confusing as Colors is a wrapper component just for presentational purposes.
Removed in Colors:
- Code Editor
- Props
> docs(colors): improve styling

- src/components/layout/FlexCol/FlexCol.tsx
- src/components/layout/FlexCol/__snapshots__/FlexCol.test.tsx.snap
- src/components/molecules/Help/__snapshots__/Help.test.tsx.snap
- src/components/molecules/ZopaFooter/Links/__snapshots__/Links.test.tsx.snap
- src/components/molecules/ZopaFooter/MiscLinks/__snapshots__/MiscLinks.test.tsx.snap
- src/components/molecules/ZopaFooter/SocialLinks/__snapshots__/SocialLinks.test.tsx.snap
- src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
Thanks to @thegrinder for finding this bug. 
Basically if we set up an alignment in the parent component of `<FlexCol />` this one get replaces as we are setting `align-self: flex-start`.
Now we set 'auto' as a default
> fix(flexcol): change align default prop

- src/components/molecules/Modal/Modal.md
- src/components/molecules/Modal/Modal.test.tsx
- src/components/molecules/Modal/Modal.tsx
- src/components/molecules/Modal/ModalStyles/ModalStyles.tsx
- src/components/molecules/Modal/__snapshots__/Modal.test.tsx.snap
Addresses #36. 
Adding a `layer` prop to `<Modal.Styles />` to control the `z-index` applied on the rendered modal,
for example:
```jsx
<NavBar /> // this is fixed and internally applies a `z-index` value of `100`
<Modal.Styles layer={200} /> // ensures `<Modal />` will always render on top of `<NavBar />`  
```
> Control applied `z-index` in `<Modal />` 👔

- src/components/atoms/InputText/InputText.tsx
Forward `ref` on `<TextInput />`.
Take it also as an opportunity to trigger a proper _minor release_ through **semantic release**. 
[My last PR](https://github.com/zopaUK/react-components/pull/40) was meant to trigger a _minor release_ also, however, I forgot to format the commit message accordingly 🤦🏻‍♂️
> Forward ref on `<TextInput />`

- src/components/molecules/TextField/TextField.tsx
- src/components/molecules/TextField/__snapshots__/TextField.test.tsx.snap
Decouple `<TextField />` **validation message** layout the size of the rendered input. 
This allows for the **validation message** to grow naturally up to the containers available width rather than having to break into a new line when there's no need.
> <TextField /> validation message layout 📐🤓

- src/components/molecules/DropdownField/DropdownField.md
- src/components/molecules/DropdownField/DropdownField.test.tsx
- src/components/molecules/DropdownField/DropdownField.tsx
- src/components/molecules/DropdownField/__snapshots__/DropdownField.test.tsx.snap
- src/components/molecules/TextField/TextField.tsx
- src/components/types.ts
- src/index.ts
Adds a new `<DropddownField />` molecule to complete the group of **"form molecules"** we have:
- `<TextField />`
- `<RadioField />`
- `<ChecboxField />`
It's a convenience so that you can use a dropdown that is stateful ( _error and help text_ ) and accessible ( _with label_ ) instead of building your own 💅🏻
I had to wrangle a bit with the types, as the native `<select>` element had already a `size` attribute which was conflicting with the `size` to customise `<SizedContainer />`.
> <DropdownField /> molecule

- src/components/icons/Alert/Alert.md
- src/components/icons/Arrow/Arrow.md
- src/components/icons/CheckMark/CheckMark.md
- src/components/icons/Chevron/Chevron.md
- src/components/icons/ZopaLogo/ZopaLogo.md
- src/index.ts
Rename our **icon components** so that they contain the word `Icon` on their name.
In this way, whenever importing one of those components is explicit that their responsibility is to render an icon 💅🏻
It is marked as a **breaking change**.
- #20
> Rename icons 💬

- src/components/molecules/ZopaFooter/Legal/Legal.test.tsx
- src/components/molecules/ZopaFooter/Legal/Legal.tsx
- src/components/molecules/ZopaFooter/Legal/__snapshots__/Legal.test.tsx.snap
- src/components/molecules/ZopaFooter/Links/Links.tsx
- src/components/molecules/ZopaFooter/Links/__snapshots__/Links.test.tsx.snap
- src/components/molecules/ZopaFooter/ZopaFooter.test.tsx
- src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
- src/helpers/test/date.ts
Changed the car finance link  to car loans and changed to dynamic copyright year in the legal text to show actual year
> fix(footer): fix car loans link and copyright year

- src/components/layout/FlexCol/FlexCol.md
- src/components/layout/FlexRow/FlexRow.tsx
- src/components/layout/FlexRow/__snapshots__/FlexRow.test.tsx.snap
- src/components/molecules/Help/__snapshots__/Help.test.tsx.snap
- src/components/molecules/ZopaFooter/Links/__snapshots__/Links.test.tsx.snap
- src/components/molecules/ZopaFooter/MiscLinks/__snapshots__/MiscLinks.test.tsx.snap
- src/components/molecules/ZopaFooter/SocialLinks/__snapshots__/SocialLinks.test.tsx.snap
- src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
Added `direction` prop to `<FlexRow>` to control order in which the columns collapse
> Add column swapping to grid

- src/components/atoms/Button/Button.md
- src/components/atoms/Card/Card.md
- src/components/atoms/Dropdown/Dropdown.tsx
- src/components/atoms/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- src/components/atoms/SidekickCard/SidekickCard.md
- src/components/organisms/Navbar/Navbar.md
- src/components/organisms/Navbar/NavbarDropdown/NavbarDropdown.md
- src/components/organisms/Navbar/NavbarLayout/NavbarLayout.md
- src/components/organisms/Navbar/NavbarLink/NavbarLink.md
- src/styleguide-components/Heading.js
- src/styleguide-components/StyleGuide.js
- src/styleguide-components/Table.js
- styleguide.config.js
When working on the [re-brand updates](https://github.com/zopaUK/react-components/pull/54) I noticed that when removing **Alverata** our docs headings looked a bit _oopsie_:
While updating the header styles... I found myself on the journey of customising our **Docs UI** with the goal of...
> Making the docs UI distinct from our components UI
Here are the updates:
- Use **system font-stack** for our docs typography
- Nicer props table ( looking like an actual table 😝 )
- Clear border to highlight properly the **component preview**
- Cleaning the sidebar to have a proper **dark theme** 🦇
Here's the result... 🥁
I understand this is a pretty stubborn change from my side, so happy not to get it merged if it not seen as an improvement 👍🏻
> Improve documentation styles 🎨 🖌 👨🏻‍🎨

- etc/rollup/config.js
- package.json
- src/components/molecules/TextField/TextField.tsx
- yarn.lock
Rollups has been updated
Terser plugin has been added to minify the compiled files
Add browserlist config as shopfront has
Remove unused config (it's already in babel-react-app-preset)
> fix(rollup): upgrade config and deps

- src/components/atoms/Heading/Heading.tsx
- src/components/atoms/Heading/__snapshots__/Heading.test.tsx.snap
Our **level 1** size in `<Heading />` ( currently `48px` ) is too big on narrow viewports.
As you can see &nbsp; ☝🏻 👀 on most mobile devices at that size, you can only fit at most *two words per line* which affects readability.
Decrease manually the font size of our `h1` to `36px` on narrow viewports:
There's a spec on the works by the **design team** on responsive font sizes ...
Related to #51
> Heading level 1 size on 📱

- src/components/atoms/Link/Link.md
- src/components/atoms/Link/Link.tsx
- src/components/atoms/Link/__snapshots__/Link.test.tsx.snap
- src/components/molecules/Help/__snapshots__/Help.test.tsx.snap
- src/components/molecules/ZopaFooter/FooterLink/__snapshots__/FooterLink.test.tsx.snap
- src/components/molecules/ZopaFooter/Links/__snapshots__/Links.test.tsx.snap
- src/components/molecules/ZopaFooter/SocialLinks/__snapshots__/SocialLinks.test.tsx.snap
- src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
- src/components/organisms/Navbar/NavbarLink/__snapshots__/NavbarLink.test.tsx.snap
A bit of cleanup on `<Link />` ...
- make it same size as its wrapping `<Text />` on the examples
- use `<Text />` instead of `a` as the **styled-components** base
- prevent it's `weight` being customisable ( _always "semibold"_ )
> Cleanup <Link /> 🛀 

- .gitignore
- etc/rollup/config.js
- package.json
- tsconfig.types.json
- yarn.lock
With the incorporation of Rollup as a bundling system, we decreased the amount of the JS by bundling in 2 single files (one for old modules and another one for ESM). At that time that was a huge improvement because the tree shaking was activated in the bundle for the new browsers (ESM) in bundling time for the library. Meaning that any unused code in the library will be excluded from the resulting bundle (which is great). 
The consumer of the library couldn't actually achieve tree shaking in his side, which is bad.
For example in my app I had a chunk with this:
This is not great because it means that all the library is bundled in the same chunk, in this case, the `vendors` chunk.
and this is the overall view: 
By enabling `preserveModules` we say to Rollup "Hey, don't add everything in a …
> Enable tree shacking in the consumer side

- src/components/atoms/SidekickCard/SidekickCard.md
- src/components/atoms/Text/Text.md
- src/components/atoms/Text/Text.test.tsx
- src/components/atoms/Text/Text.tsx
Already in existing designs (👇 **Savings Dashboard** )
and new ones (👇 **Shopfront new BP page** )
Paragraphs of text `<p>` appear with the `<h4>` font size ( `20px` ).
At the moment, `<Text />` only renders at `16px` or `14px` but **the design team
has approved** the need to add an option to render it at `20px`.
This PR brings that new size to `<Text />`:
```jsx
<Text size="lead">Wooohoo I render big and nice at 20px</Text>
```
Note that this doesn't break our new [typography spec](https://user-images.githubusercontent.com/5938217/65140301-85298980-da0e-11e9-82cc-2a541449d660.png)... when designed it wasn't taken in account the semantics needed on the web ( _for instance in the **mobile app** is fine to mark long text as a **heading 4**..._ )
> <Text size="lead" />

- src/helpers/responsiveness.ts
After my [last PR](#127) a bug was introduced where the responsive helpers `minMedia` and `maxMedia` are not typed properly.
Currently they are typed as receiving **only** an array of [template strings](https://github.com/zopaUK/react-components/blob/master/src/helpers/responsiveness.ts#L25-L29), hence doing this is fine:
```js
maxMedia`font-size: 14px;`
```
as it translates roughly to:
```js
maxMedia(['font-size: 14px;'])
```
however if we pass a dynamic value:
```js
maxMedia`font-size: ${mySize};`
```
it translates to:
```js
maxMedia(['font-size: ', ';'], mySize)
```
and hence  **Typescript** will complain that `maxMedia` expects one argument but two were supplied. 
( _you can learn how tagged templates work [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Templat …
> Interpolate function typing  😅

- src/components/layout/FlexCol/FlexCol.test.tsx
- src/components/layout/FlexCol/FlexCol.tsx
- src/components/layout/FlexCol/__snapshots__/FlexCol.test.tsx.snap
- src/components/layout/FlexRow/FlexRow.tsx
Addressing #154, following my last PR on types I forgot to make `<FlexCol />` also extend `HTMLAttributes`  💆🏻‍♂️
I added a couple more tests on `<FlexCol />` to improve coverage, as **Codecov** was complaining about it 🌧
> <FlexCol /> should inherit native HTML types as well

- README.md
I was publishing them manually on every release... 
Time has passed ⏰ , I think most of the clients of this library are now on **v2** so I think there's no need to keep the **v1** docs accessible anymore.
> Remove reference to v1 docs

- package.json
- yarn.lock
In order to not force users to manually install the react-modal types I'm moving it from dev dependencies to dependencies.
> fix(react-modal): move types from dev dependencies to dependencies

- package.json
- src/components/molecules/Tooltip/Tooltip.md
- src/components/molecules/Tooltip/Tooltip.test.tsx
- src/components/molecules/Tooltip/Tooltip.tsx
- src/components/molecules/Tooltip/__snapshots__/Tooltip.test.tsx.snap
- src/index.ts
- yarn.lock
New `<Tooltip />` component which in turns is just a wrapper over [`@tippy.js/react`](https://github.com/atomiks/tippy.js) with design constraints applied on top.
**Tippy JS** handles already a lot of the edge-cases associated to tooltips for us ( 👀  **"Adaptability"** section below ) and make sure [they stay as accessible as possible](https://atomiks.github.io/tippyjs/accessibility/#interactivity). 
This comes with an import cost though ☝🏻 ( what do you think @poteirard ? ) but at least we think is safer and more performant than any custom solution we could engineer...  
( &nbsp;👀  _notice how the tooltip vertical alignment changes..._ )
( &nbsp;👀 _notice how the tooltip horizontal alignment changes..._ )
> New <Tooltip />  component 🧪

- src/components/hooks/useForm/FormContext.ts
- src/components/hooks/useForm/index.ts
- src/components/hooks/useForm/useFieldContext.ts
- src/components/hooks/useForm/useForm.test.ts
- src/components/hooks/useForm/useForm.ts
- src/components/hooks/useForm/useFormContext.test.ts
- src/components/hooks/useForm/useFormContext.ts
- src/components/molecules/DropdownFiltered/DropdownFiltered.md
- src/components/organisms/Form/Form/Form.tsx
- src/components/organisms/Form/FormButton/FormButton.tsx
- src/components/organisms/Form/FormCheckboxField/FormCheckboxField.tsx
- src/components/organisms/Form/FormDropdownField/FormDropdownField.tsx
- src/components/organisms/Form/FormDropdownFilteredField/FormDropdownFilteredField.tsx
- src/components/organisms/Form/FormRadioField/FormRadioField.tsx
- src/components/organisms/Form/FormTextField/FormTextField.tsx
- src/components/organisms/Form/context/FormContext.ts
- src/components/organisms/Form/context/index.ts
- src/components/organisms/Form/context/useFieldContext.ts
- src/index.ts
- Move `FormContext`, `useFormContext`, and `useFieldContext` to `hooks` folder
- Export these hooks as they might be needed to create custom input components (e.g. to add `onChange`, you need to grab and call the original one you get from context through `useFieldContext`)
- Export hook types (all of them had to be reexported because of this https://github.com/facebook/create-react-app/issues/6054)
> Move and expose form hooks and reexport their types

- src/components/hooks/useForm/useForm.test.ts
- src/components/hooks/useForm/useForm.ts
- src/components/organisms/Form/Form/Form.test.tsx
- src/components/organisms/Form/Form/Form.tsx
Add `onChange` prop to `useForm` and `<Form />`. This is useful in case you need custom input that consists of various small sub-inputs (e.g. date input)
> Add form on change

- src/components/atoms/Dropdown/Dropdown.tsx
- src/components/molecules/DropdownField/DropdownField.tsx
- src/components/molecules/TextField/TextField.test.tsx
- src/components/molecules/TextField/TextField.tsx
- src/components/organisms/Form/FormDropdownField/FormDropdownField.tsx
- src/components/organisms/Form/FormTextField/FormTextField.tsx
Forward refs to all `<input />` and `<select />` elements to be able to, for example, programatically focus on an element.
> Forward refs in inputs

- CODEOWNERS
A few weeks ago we added [`renovate-bot`](https://renovate.whitesourcesoftware.com/) to do minor dependency upgrades ( `0.*.0` and `0.0.*` )  for us automatically. 
The bot [raises a PR](https://github.com/zopaUK/react-components/pull/214) for each upgrade, however, given our `master` branch is protected 🔐 ,  we need to manually approve and merge each PR, which can end tedious.
We have now added a second bot, [`renovate-approve`](https://github.com/apps/renovate-approve) so that it can approve and merge those PRs for us. This a **POC** to see how it works for us.
> Add approve bot to CODEOWNERS 🤖

- CODEOWNERS
> If you need to add this bot to your CODEOWNERS, you can identify it using app/renovate-approve.
So seems I shouldn't reference `app/renovate-bot` with an `@` as it has not being recognised as a `CODEOWNER` successfully 😅
> Update CODEOWNERS again... 🤖

- package.json
- yarn.lock
Types were broken in the [latest build of `master`](https://circleci.com/gh/zopaUK/react-components/2185?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) due to duplicate declarations, check [this issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33822).
> Upgrade lock file 🔑

- src/components/atoms/InputText/InputText.tsx
- src/components/atoms/InputText/__snapshots__/InputText.test.tsx.snap
- src/components/molecules/CheckboxField/CheckboxField.tsx
- src/components/molecules/CheckboxField/__snapshots__/CheckboxField.test.tsx.snap
- src/components/molecules/DropdownField/DropdownField.md
- src/components/molecules/DropdownField/DropdownField.tsx
- src/components/molecules/DropdownField/__snapshots__/DropdownField.test.tsx.snap
- src/components/molecules/DropdownFiltered/DropdownFiltered.tsx
- src/components/molecules/DropdownFiltered/__snapshots__/DropdownFiltered.test.tsx.snap
- src/components/molecules/RadioField/RadioField.tsx
- src/components/molecules/RadioField/__snapshots__/RadioField.test.tsx.snap
- src/components/molecules/TextField/TextField.tsx
- src/components/molecules/TextField/__snapshots__/TextField.test.tsx.snap
The _white-space_ after the **label** on `<TextField />` was off. I suspect it comes from [an update we did in `<InputLabel />`](https://github.com/zopaUK/react-components/pull/170) a few weeks ago.
I made the spacing consistent as well in `<DropdownField />` and `<DropdownFiltered />`.
There was a default `margin-bottom` applied without need to `<RadioField />` and `<CheckboxField />`. I removed it and made it appear only when more than one element is rendered through `:last-of-type`. 💭
This might justify picking up again [the spike on visual diff](https://github.com/zopaUK/react-components/issues/14) with [Percy](percy.io/).
> <*Fiel /> components → Adjust childs spacing 😐 📐

- src/components/atoms/InputText/InputText.tsx
- src/components/atoms/InputText/__snapshots__/InputText.test.tsx.snap
- src/components/molecules/DropdownFiltered/__snapshots__/DropdownFiltered.test.tsx.snap
- src/components/molecules/TextField/__snapshots__/TextField.test.tsx.snap
In this library, we make use of [`styled-normalise`](https://github.com/sergeysova/styled-normalize) ( _which is just a wrapper over [`normalise.css`](https://github.com/necolas/normalize.css)_ ) to ensure consistency on the **browser's native CSS**.
Recently we noticed our input's placeholder looked _dimmer_ on Firefox, seems that `normalise.css` is [not normalising that anymore](https://github.com/necolas/normalize.css/issues/741) due to a bug on Edge 🦟
https://github.com/zopaUK/react-components/issues/243
> Adjust placeholder styles 💄

- src/components/organisms/Form/hooks/useForm.test.ts
- src/components/organisms/Form/hooks/useForm.ts
- make `onSubmit` optional because it's sometimes not needed, especially in case of subforms that rely mostly on form's `onChange`
- pass through `initialValues` as some more complex forms require comparison of initial values with current form values
> Small form fixes

- src/components/molecules/ZopaFooter/ZopaFooter.tsx
- src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
Semantics 💄 💓
I removed an `id` present there, if consumers still need they can just do:
```jsx
<ZopaFotter id="zopa-footer" />
```
> Render `<footer />` not `<div />`

- src/components/organisms/Navbar/Navbar/Navbar.tsx
- src/constants/components.ts
- src/index.ts
Many times is helpful for the clients of this library to be able to read programmatically the height of `<Navbar />` and adjust their layouts accordingly ( _if needed_ ).
> Export `<Navbar />` height 📐

- src/components/atoms/Link/Link.tsx
- src/components/atoms/Link/__snapshots__/Link.test.tsx.snap
- src/components/molecules/Help/__snapshots__/Help.test.tsx.snap
- src/components/molecules/ZopaFooter/Links/Links.tsx
- src/components/molecules/ZopaFooter/Links/__snapshots__/Links.test.tsx.snap
- src/components/molecules/ZopaFooter/SocialLinks/__snapshots__/SocialLinks.test.tsx.snap
- src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
- src/components/organisms/Navbar/NavbarLink/__snapshots__/NavbarLink.test.tsx.snap
- src/constants/colors.ts
```jsx
<Link color />
```
This prop was typed as `any` given previously this component was extending `<Text />` and **TS** was getting a mess with the `color` props.
Now that it just extends `styled.a` type it properly...
https://github.com/zopaUK/react-components/issues/139
> Type link color properly 🧼

- README.md
Our types are not exported in the root of the package, given there's [an issue with Webpack](https://github.com/babel/babel-loader/issues/603#issuecomment-583269261).
They're exported under `@zopauk/react-components/types`, document that given people might be easily confused around it 👍🏻
#212
> Document how to access typings 🕵🏻‍♂️

- src/hooks/useViewport/ViewportProvider.tsx
- src/hooks/useViewport/context.ts
- src/hooks/useViewport/types.ts
- src/hooks/useViewport/useViewport.ts
Address circular dependencies in `useViewport` surfaced when compiling the library 😇
```
src/hooks/useViewport/useViewport.ts:22:17 - error TS4058: Return type of exported function has or is using name 'IViewportSize' from external m
odule "/Users/lluis.agusti/Code/zopa-react-components/src/hooks/useViewport/ViewportProvider" but cannot be named.
22 export function useViewport({ timeout = 300 }: IUseViewportOptions = {}) {
```
> Compile errors 🧜🏼‍♂️

- src/components/atoms/Card/Card.tsx
- src/components/atoms/Card/__snapshots__/Card.test.tsx.snap
Fix card styling so that it follows mobile-first approach (i.e. uses `min-width` instead of `max-width` media queries)
> fix(card): fix card styling to follow mobile-first approach

- src/components/molecules/DropdownFiltered/DropdownFiltered.tsx
Don't overwrite dropdown's input `onChange` and `onFocus`
> fix(dropdownfiltered): don't overwrite input's onChange and onFocus

- src/components/atoms/InputText/InputText.tsx
- src/components/atoms/InputText/__snapshots__/InputText.test.tsx.snap
- src/components/molecules/DropdownFiltered/__snapshots__/DropdownFiltered.test.tsx.snap
- src/components/molecules/TextField/__snapshots__/TextField.test.tsx.snap
InputText
In some versions of Safari it was adding an extra border
> fix(InputText): remove webkit appearance

- src/components/atoms/InputText/InputText.tsx
- src/components/atoms/InputText/__snapshots__/InputText.test.tsx.snap
- src/components/molecules/DropdownFiltered/__snapshots__/DropdownFiltered.test.tsx.snap
- src/components/molecules/TextField/__snapshots__/TextField.test.tsx.snap
outline in input text is still present in some safari versions 🤷‍♂
> fix(inputtext): remove outline at all

- src/components/molecules/Help/Help.tsx
- src/components/molecules/Help/__snapshots__/Help.test.tsx.snap
There is no gap between the links and the Opening Hours for screens lower than `l` size.
This PR is to fix this small issue.
Example:
> fix(help): fix weird spacing for Help section

- src/components/atoms/Button/Button.test.tsx
- src/components/atoms/Button/Button.tsx
- src/components/atoms/Button/__snapshots__/Button.test.tsx.snap
On a [previous PR](https://github.com/zopaUK/react-components/pull/291) where I rebranded our `<Button />` component, I missed [the existing `type` prop](https://github.com/zopaUK/react-components/blob/master/src/components/atoms/Button/Button.tsx#L14). This PR brings it back 😇
> Bring back <Button type /> prop 🙇🏻‍♂️

- src/README.md
- src/components/styles/Spacing.ts
Avoid the polyfill for CSS escape by manually escaping the `:` also updated documentation with the correct spacing.
> Avoid Css polyfill and documentation updates

- src/components/atoms/AlertBox/AlertBox.tsx
- src/components/icons/Alert/Alert.tsx
- src/components/icons/Arrow/Arrow.tsx
- src/components/icons/CheckMark/CheckMark.tsx
- src/components/icons/Chevron/Chevron.tsx
- src/components/icons/Hamburger/Hamburger.tsx
- src/components/icons/Profile/Profile.tsx
Deprecate existing icon components using [`util-deprecate`](https://www.npmjs.com/package/util-deprecate) and point to which **font-awesome** icons to use instead.
[ZDS-11](https://jira.zopa/browse/ZDS-11)
> Deprecate existing icon components 🗑

- src/components/atoms/InputRange/InputRange.md
- src/components/atoms/InputRange/InputRange.test.tsx
- src/components/atoms/InputRange/InputRange.tsx
- src/components/atoms/InputRange/__snapshots__/InputRange.test.tsx.snap
- src/components/atoms/InputRange/helpers/helpers.test.ts
- src/components/atoms/InputRange/helpers/index.ts
- src/components/atoms/README.md
- src/index.ts
I will add controls in a new Molecule (in a new PR). Still thinking in a proper name, I will go with
InputRangeWithControls for now.
Notes: This is a v3 version of the InputRange. We will add correct colors and states in v4.
Related JIRA: https://jira.zopa/browse/SHOPDEV-6087
> feat(inputrange): adding Input Range without controls

- src/components/atoms/InputRange/InputRange.md
- src/components/atoms/InputRange/InputRange.test.tsx
- src/components/atoms/InputRange/InputRange.tsx
This is to avoid issues with inputRef. Also, this component will always be used as a controlled component.
> fix(inputrange): make InputRange controlled only

- CONTRIBUTING.md
- src/README.md
- src/content/Colors/Colors.md
- src/content/Spacing/Spacing.md
- src/content/Spacing/Spacing.tsx
The new **spacing docs** were in the main **Introduction** section.
I decided to move them to their own section ( _as we do with **colours**_ ) so they gain visibility and hopefully, developers start using them.
I re-worded the content a bit as well and extended the examples to hopefully lessen confusion around them.
> Move spacing docs to their own section

- src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
- src/components/molecules/ZopaFooter/styles/Footer.tsx
`<ZopaFooter />` will always need to have white background.
- set white background
- use `padding-bottom` instead of `margin-bottom`
> fix(zopafooter): set white background color

- src/components/atoms/Button/Button.md
- src/components/atoms/Button/Button.test.tsx
- src/components/atoms/Button/Button.tsx
- src/components/atoms/Button/__snapshots__/Button.test.tsx.snap
A `<Button />` that's rendered with the `loading` option should also be `disabled` (not clickable) but it should keep most of the loading button styles.
Whenever the button is set to be `loading`, its `disabled` attribute is also set to true.
The disabled `background` and `color` styles are not applied when the button is both `loading` and `disabled`.
> fix(button): always render loading button with disabled attribute

- package.json
- src/components/atoms/ErrorMessage/ErrorMessage.tsx
- src/components/atoms/ErrorMessage/__snapshots__/ErrorMessage.test.tsx.snap
Fixes the error messages for small widths and also add max-width like it was before
Before:
> Fix error message

- src/components/organisms/Navbar/NavbarDropdown/NavbarDropdown.md
- src/components/organisms/Navbar/NavbarDropdown/NavbarDropdown.test.tsx
- src/components/organisms/Navbar/NavbarDropdown/NavbarDropdown.tsx
- src/components/organisms/Navbar/NavbarDropdown/NavbarDropdownList/NavbarDropdownList.test.tsx
- src/components/organisms/Navbar/NavbarDropdown/NavbarDropdownList/NavbarDropdownList.tsx
- src/components/organisms/Navbar/NavbarDropdown/NavbarDropdownList/__snapshots__/NavbarDropdownList.test.tsx.snap
- src/components/organisms/Navbar/NavbarDropdown/__snapshots__/NavbarDropdown.test.tsx.snap
- src/components/organisms/Navbar/NavbarLinksList/NavbarLinksList.md
- src/components/organisms/Navbar/NavbarLinksList/NavbarLinksList.test.tsx
- src/components/organisms/Navbar/NavbarLinksList/NavbarLinksList.tsx
- src/components/organisms/Navbar/NavbarLinksList/__snapshots__/NavbarLinksList.test.tsx.snap
There is no need to keep the `renderOpener` prop as the navbar dropdowns should always be consistent when it comes to toggle buttons
> fix(navbar): remove renderOpener and rename ariaLabel to just label

- src/components/atoms/Alert/Alert.tsx
I've got some errors when using `<Alert />` component. I was unable to add `className` prop to it. This PR is to fix this type error.
> fix(alert): fix props for Alert component

- src/components/organisms/Navbar/Navbar/__snapshots__/Navbar.test.tsx.snap
- src/components/organisms/Navbar/NavbarDropdown/__snapshots__/NavbarDropdown.test.tsx.snap
- src/components/organisms/Navbar/NavbarLink/NavbarLink.tsx
- src/components/organisms/Navbar/NavbarLink/__snapshots__/NavbarLink.test.tsx.snap
- src/components/organisms/Navbar/NavbarLinksList/__snapshots__/NavbarLinksList.test.tsx.snap
Issue (in Shopfront) with `:active` links:
> fix(navbarlink): force color to navbar links

- src/components/molecules/CheckboxField/CheckboxField.tsx
- src/components/molecules/CheckboxField/__snapshots__/CheckboxField.test.tsx.snap
> fix(checkboxfield): fix checkbox and label alignment

- src/components/molecules/ExpiryModal/ExpiryModal.tsx
As mentioned in the issue there's no need to show the cross icon in `ExpiryModal`
Fixes #502
> fix(expiry modal): do not show the cross button

- src/components/organisms/Navbar/Navbar/Navbar.tsx
- src/components/organisms/Navbar/NavbarLink/NavbarLink.tsx
- src/components/organisms/Navbar/OpenProvider.tsx
- src/components/organisms/Navbar/index.tsx
Design/UX asked to let the user close the hamburger menu when clicking the same link as the current page.
This PR is to do this tricky logic.
> fix(navbar): close hamburger menu on link click

- src/components/organisms/Navbar/Navbar/Navbar.tsx
Exclude won't remove `setOpen`, Omit will do.
> fix(navbar): fix props for Navbar

- src/components/atoms/Dropdown/Dropdown.tsx
- src/components/atoms/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- src/components/atoms/InputText/InputText.tsx
- src/components/atoms/InputText/__snapshots__/InputText.test.tsx.snap
- src/components/molecules/DropdownFiltered/__snapshots__/DropdownFiltered.test.tsx.snap
- src/components/molecules/TextField/__snapshots__/TextField.test.tsx.snap
- fix disabled input styling on safari
- remove safari's default outline in `<Dropdown />`
Before:
After:
> Fix disabled input styling on safari

- src/components/atoms/Button/__snapshots__/Button.test.tsx.snap
- src/components/atoms/Spinner/Spinner.tsx
- src/components/atoms/Spinner/__snapshots__/Spinner.test.tsx.snap
- src/components/molecules/RadioField/RadioField.tsx
- src/components/molecules/RadioGroupField/RadioGroupField.md
- src/components/molecules/RadioGroupField/RadioGroupField.tsx
- src/components/types.ts
- Fixes spinner on mobile view
- Removes loader on radio field
- Allows a react node to be passed in for an item label on radio field
> Fix spinner on mobile view

- src/components/atoms/Dropdown/Dropdown.tsx
- src/components/atoms/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- src/components/atoms/InputText/InputText.tsx
- src/components/atoms/InputText/__snapshots__/InputText.test.tsx.snap
- src/components/molecules/CheckboxField/CheckboxField.tsx
- src/components/molecules/CheckboxField/__snapshots__/CheckboxField.test.tsx.snap
- src/components/molecules/CheckboxGroupField/__snapshots__/CheckboxGroupField.test.tsx.snap
- src/components/molecules/DropdownFiltered/__snapshots__/DropdownFiltered.test.tsx.snap
- src/components/molecules/RadioField/RadioField.tsx
- src/components/molecules/RadioGroupField/__snapshots__/RadioGroupField.test.tsx.snap
- src/components/molecules/TextField/__snapshots__/TextField.test.tsx.snap
Add greyLightest  background  color to disable state for
- Dropdown
- InputText
- RadioField
- CheckBoxField
> fix(inputs): add background color on disabled state

- src/components/atoms/Alert/Alert.tsx
- src/components/molecules/Notification/__snapshots__/Notification.test.tsx.snap
Rounded corners in the Alert component are **too** round - reducing from 12px to 4px.
> fix(alert): set radius to 4px

- src/components/molecules/NumberText/NumberText.test.tsx
- src/components/molecules/NumberText/NumberText.tsx
When a value of 0 is passed as a value prop it should render as £0.00
> feat(number text): deal with 0 values

- src/components/molecules/NumberText/NumberText.test.tsx
- src/components/molecules/NumberText/NumberText.tsx
- src/components/molecules/NumberText/__snapshots__/NumberText.test.tsx.snap
Make it possible to have left aligned text that is vertically centered in the NumberText component.
> fix[numberText]: fix alignment in number text

- src/components/organisms/Navbar/Navbar/Navbar.md
- src/components/organisms/Navbar/Navbar/Navbar.tsx
- src/components/organisms/Navbar/Navbar/__snapshots__/Navbar.test.tsx.snap
**The issue**
react-headroom adds a height to the navbar wrapper and only updates when a user resizes the screen. this would cause it to have a height of 120px on page load and not change after scrolling, preventing users from click up to 50px under the navbar
**The solution**
add max-height on navbar-wrapper
> Navbar headroom

- src/components/atoms/Text/Text.tsx
A component I'm working on requires a `<figcaption>` element within a `<figure>` element, which contains an image and a string of text. This small PR add the appropriate type to the `<Text/>` component
> feat(text): as includes figcaption

- src/components/atoms/Dropdown/Dropdown.tsx
- src/components/atoms/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- src/components/organisms/Tabs/TabButtons/__snapshots__/TabButtons.test.tsx.snap
The dropdown field cuts off letters such as "g / q"
FYI This doesn't affect the height of the dropdown
> Update dropdown line height

- src/components/organisms/Accordion/AccordionHeader/AccordionHeader.tsx
- src/components/organisms/Accordion/AccordionHeader/__snapshots__/AccordionHeader.test.tsx.snap
Add `type="button"` to `AccordionHeader` to prevent submission of forms when clicking on accordion
https://github.com/formium/formik/issues/1610
> fix(accordion): add type='button' to header

- package.json
- pnpm-lock.yaml
Fix security:
**GHSA-r2j6-p67h-q639**
**high severity**
**Vulnerable versions:** <= 17.2.2
**Patched version:** 17.2.3
Secrets that would normally be masked by semantic-release can be accidentally disclosed if they contain characters that become encoded when included in a URL.
Fixed in v17.2.3
Secrets that do not contain characters that become encoded when included in a URL are already masked properly.
> chore(release): update semantic-release

- src/components/molecules/Progress/Progress.tsx
- src/components/molecules/Progress/__snapshots__/Progress.test.tsx.snap
- src/components/organisms/Tabs/TabButtons/__snapshots__/TabButtons.test.tsx.snap
- src/components/organisms/Tabs/TabsContainer/__snapshots__/TabsContainer.test.tsx.snap
- src/components/templates/ProductTemplate/ProductTemplate/ProductTemplate.test.tsx
- src/components/templates/ProductTemplate/ProductTemplate/ProductTemplate.tsx
- src/components/templates/ProductTemplate/ProductTemplate/__snapshots__/ProductTemplate.test.tsx.snap
- src/components/templates/ProductTemplate/ProductTemplateHeader/ProductTemplateHeader.test.tsx
- src/components/templates/ProductTemplate/ProductTemplateHeader/__snapshots__/ProductTemplateHeader.test.tsx.snap
- src/components/templates/ProductTemplate/ProductTemplateNavigation/ProductTemplateNavigation.test.tsx
- src/components/templates/ProductTemplate/ProductTemplateProgress/__snapshots__/ProductTemplateProgress.test.tsx.snap
- src/components/templates/ProductTemplate/ProductTemplateTitle/ProductTemplateTitle.tsx
- src/components/templates/ProductTemplate/ProductTemplateTitle/__snapshots__/ProductTemplateTitle.test.tsx.snap
Updated `ProductTemplate` designs with optional title.
`title` now an optional property of `<ProductTemplate />`. Rendering without title will overlay the
content slightly higher leaving only 24px of margin.
> feat(product template): render ProductTemplate without title

- src/components/organisms/Tabs/TabButtons/__snapshots__/TabButtons.test.tsx.snap
- src/components/organisms/Tabs/TabsContainer/__snapshots__/TabsContainer.test.tsx.snap
- src/components/templates/ProductTemplate/ProductTemplate/ProductTemplate.tsx
- src/components/templates/ProductTemplate/ProductTemplate/__snapshots__/ProductTemplate.test.tsx.snap
- src/components/templates/ProductTemplate/ProductTemplateTitle/ProductTemplateTitle.tsx
- src/components/templates/ProductTemplate/ProductTemplateTitle/__snapshots__/ProductTemplateTitle.test.tsx.snap
- src/components/templates/ProductTemplate/README.md
Allow ProductTemplate to host optional product specific content.
```tsx
<ProductTemplate
title="Product title"
subtitle="Product subtitle"
content={<div>custom content here</div>}
>
<ProductTemplate.Card>This is the body of the card.</ProductTemplate.Card>
</ProductTemplate>
```
> feat(producttemplate): add optional content to product template

- package.json
Relaxing the range as this is currently needlessly restrictive as TypeScript does not follow semver and there is nothing here that should break TypeScript clients. Its arguable if TypeScript should even be a peer - but this is for another issue.
> relaxes typescript peer range to be >= 3

- src/components/molecules/ZopaFooter/ZopaFooter.tsx
- src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
- Add aria-label to announce the link purpose for screen readers
- Use title to warn a user that link opens in a new tab
The link will be announced like e.g. `Link, Twitter. Twitter opens in a new tab. You are currently on a Link.`
> Change external links attributes to improve screen-readers experience

- src/components/molecules/ZopaFooter/ZopaFooter.tsx
- src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
Changing the blog url in the footer from blog.zopa.com to zopa.com/blog
> fix: Updating the Blog url to /blog

- src/components/organisms/Navbar/Navbar/Navbar.tsx
- src/components/organisms/Navbar/NavbarDropdown/NavbarDropdown.tsx
Currently HotJar cannot suppress user names in the navbar. This change means we can now add the suppression tag in react-libs to do so and hide all user information in screen recordings.
It's quite clunky, but `aria-label` can only take a string type, we've added a new property `aria-label` which will be set to `undefined` if it receives a label which isn't of type string.
> fix(navbar): allows us to suppress user info in navbar with hotjar

- src/components/organisms/Accordion/AccordionSection/AccordionSection.tsx
- src/components/organisms/Accordion/AccordionSection/__snapshots__/AccordionSection.test.tsx.snap
As per this axe rule content inside of aria-hidden should not be focusable.
https://dequeuniversity.com/rules/axe/4.2/aria-hidden-focus?application=axeAPI
> fix(a11y): accordion needs tab index -1 when aria hidden

- src/components/molecules/RadioField/RadioField.md
- src/components/molecules/RadioField/RadioField.tsx
- src/components/molecules/RadioField/__snapshots__/RadioField.test.tsx.snap
- src/components/molecules/RadioGroupField/__snapshots__/RadioGroupField.test.tsx.snap
**Motivation**
- According to the Zopa design system, a radio button without the control circle should have bold text which is center aligned
**What has changed**
- the hideControl prop in `RadioField` component now decides whether the text will be bold and center aligned
- Updated relevant snapshots
> Fix radiofield

- src/components/organisms/Accordion/AccordionSection/AccordionSection.tsx
- src/components/organisms/Accordion/AccordionSection/__snapshots__/AccordionSection.test.tsx.snap
Toggle visibility on content based on if the accordion is open so that you cant tab into any focusable elements
By checking the `visible={sectionPropsRest['aria-hidden']}` we can determine if the accordion is open and toggle `visibility: ${({ visible }) => (visible ? 'hidden' : 'visible')};` with `styled-components` 
- [Jira issue](https://jira.zopa/browse/SHOPDEV-8703)
> fix(accordionsection): add visibility to content

- src/components/molecules/ZopaFooter/ZopaFooter.tsx
- src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
removing 'new products' from ZopaFooter as /feelgood page no longer exists
https://jira.zopa/browse/SHOPDEV-8774
> fix(zopafooter): removing 'new products' link

- src/components/molecules/ZopaFooter/ZopaFooter.tsx
- src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
removing ISA link and moving P2P link to about section
> fix(zopafooter): removing ISA link

- src/components/atoms/Alert/Alert.tsx
- src/index.ts
Export severity type so it can be used consistently in customer components outside of library.
> feat: export severity type

- src/components/atoms/Text/Text.md
- src/components/atoms/Text/Text.test.tsx
- src/components/atoms/Text/Text.tsx
We are starting to require text to be alert dark coloured in upcoming designs so this change will be required.
> Add-alert-dark-as-text-color

- src/components/atoms/Button/Button.md
- src/components/atoms/Button/Button.tsx
- src/index.ts
Using Generics allow the button type to extend anchor tag HTML attributes
> feat(button): update types

- src/components/styles/Theme.tsx
This allows dynamically passing in a theme - if it's undefined it just defaults to the Zopa theme
> feat: allow passing an undefined theme to ThemeProvider

- src/components/atoms/Heading/Heading.md
- src/components/atoms/Heading/Heading.tsx
- src/components/molecules/NumberText/NumberText.tsx
- src/components/molecules/NumberText/__snapshots__/NumberText.test.tsx.snap
- src/components/organisms/Card/CardHeading/CardHeading.tsx
- src/components/organisms/Form/FormSection/__snapshots__/FormSection.test.tsx.snap
- src/components/styles/Theme.tsx
- src/components/templates/ErrorPages/FiveHundred/__snapshots__/FiveHundred.test.tsx.snap
- src/components/templates/ErrorPages/Four0Four/__snapshots__/Four0Four.test.tsx.snap
- src/components/templates/ErrorPages/Maintenance/__snapshots__/Maintenance.test.tsx.snap
- All <Heading/> uses which are wrapped in styled components should now pass 'forwardedAs' in place of the 'as' prop.
- Docs for forwardedAs: https://styled-components.com/docs/api#forwardedas-prop
Add theming to Heading component
Actual JL component:
Miro designs:
Rezza2 with JL font:
> Add theming to heading

- src/components/molecules/ZopaFooter/ZopaFooter.tsx
- src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
- src/components/molecules/ZopaFooter/styles/Footer.tsx
- src/components/molecules/ZopaFooter/styles/LegalBlock.tsx
- src/components/styles/Theme.tsx
Add theming to ZopaFooter to be able to:
- show/hide `LogoBlock`, `LegalBlock` and `SocialBlock`
- stretch `LegalBlock` full width 
- add optional `legalAmendment` prop to amend `LegalBlock`
> Add theming to footer

- src/components/molecules/ZopaFooter/ZopaFooter.tsx
- src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
- src/components/molecules/ZopaFooter/styles/Footer.tsx
- src/components/molecules/ZopaFooter/styles/LegalBlock.tsx
- src/components/styles/Theme.tsx
- refactor `Footer` wrapper with Tailwind & add classname to footer type to be able to change padding with theme
- refactor to get text color for `LegalBlock` from theme 
- reorganise footer theme type
> fix(zopafooter): theming bug

- src/components/atoms/Link/Link.tsx
- src/components/atoms/Link/__snapshots__/Link.test.tsx.snap
- src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
- src/components/organisms/Carousel/Carousel/__snapshots__/Carousel.test.tsx.snap
- src/components/organisms/Carousel/CarouselSlide/__snapshots__/CarouselSlide.test.tsx.snap
- src/components/organisms/Navbar/Navbar/__snapshots__/Navbar.test.tsx.snap
- src/components/organisms/Navbar/NavbarDropdown/__snapshots__/NavbarDropdown.test.tsx.snap
- src/components/organisms/Navbar/NavbarLink/__snapshots__/NavbarLink.test.tsx.snap
- src/components/organisms/Navbar/NavbarLinksList/__snapshots__/NavbarLinksList.test.tsx.snap
- src/components/templates/ErrorPages/FiveHundred/__snapshots__/FiveHundred.test.tsx.snap
- src/components/templates/ErrorPages/Four0Four/__snapshots__/Four0Four.test.tsx.snap
- src/components/templates/ErrorPages/Maintenance/__snapshots__/Maintenance.test.tsx.snap
- src/components/templates/ProductTemplate/ProductTemplateHeader/__snapshots__/ProductTemplateHeader.test.tsx.snap
- src/components/templates/ProductTemplate/ProductTemplateNavigation/__snapshots__/ProductTemplateNavigation.test.tsx.snap
- svgs as links take up `hover` and `active` color from theme
> fix(link): add theme to svg hover and active styles

- src/components/molecules/ZopaFooter/ZopaFooter.tsx
- src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
The previous implementation meant that the colour of the additional footer text had to be handled separately from the footer itself. This change allows the text to be handled the same way regardless of source.
> fix: update footer copy handler for more consistency

- src/components/templates/ErrorPages/FiveHundred/FiveHundred.tsx
- src/components/templates/ErrorPages/Four0Four/Four0Four.tsx
- src/components/templates/ErrorPages/Maintenance/Maintenance.tsx
- add `ThemeProvider` wrapper to error pages to be able to pass theme to components within these templates
> Add theme to error pages

- etc/rollup/config.mjs
Rollup causes issues with the default settings for apps (*.div is not a function etc)
See: https://github.com/rollup/rollup/issues/3684
> build(rollup): use interop: 'auto'

- src/components/molecules/ZopaFooter/ZopaFooter.md
- src/components/molecules/ZopaFooter/ZopaFooter.test.tsx
- src/components/molecules/ZopaFooter/ZopaFooter.tsx
We need to be able to pass multiline copy, so piggybacking on the additionalCopy implementation to allow us to do this.
Test and Styleguide updated.
> feat(zopafooter): allow us to have multiline legal copy in the footer

- src/components/molecules/Help/Help.tsx
- src/components/molecules/Help/__snapshots__/Help.test.tsx.snap
use greyDarkest in order for regular text in Help component to be compliant with WCAG AA
> fix(help): colour change for regular text in Help

- src/components/atoms/Alert/Alert.tsx
- src/components/atoms/Alert/__snapshots__/Alert.test.tsx.snap
- src/components/molecules/Banner/__snapshots__/Banner.test.tsx.snap
- src/components/molecules/Notification/__snapshots__/Notification.test.tsx.snap
As per design request 
Before:
After:
> style: made font size of links inside alert 16px (from 15px) 

- .changeset/angry-horses-judge.md
- package.json
- src/components/atoms/Button/__snapshots__/Button.test.tsx.snap
- src/components/atoms/RoundButton/__snapshots__/RoundButton.test.tsx.snap
- src/components/atoms/Spinner/Spinner.tsx
- src/components/atoms/Spinner/__snapshots__/Spinner.test.tsx.snap
Using alt on img tag is more appropriate that using aria-label as alt is for graphic context
> fix(spinner): spinner to use alt instead of aria-label

- .changeset/stale-forks-walk.md
- src/components/atoms/Button/Button.tsx
- src/components/atoms/Button/__snapshots__/Button.test.tsx.snap
- src/components/molecules/BankDetails/__snapshots__/BankDetails.test.tsx.snap
- src/components/molecules/Help/__snapshots__/Help.test.tsx.snap
- src/components/organisms/Navbar/Navbar/__snapshots__/Navbar.test.tsx.snap
- src/components/organisms/Navbar/NavbarAction/__snapshots__/NavbarAction.test.tsx.snap
- src/components/organisms/Tabs/TabButton/__snapshots__/TabButton.test.tsx.snap
- src/components/organisms/Tabs/TabButtons/__snapshots__/TabButtons.test.tsx.snap
- src/components/organisms/Tabs/TabsContainer/__snapshots__/TabsContainer.test.tsx.snap
- src/components/templates/ErrorPages/FiveHundred/__snapshots__/FiveHundred.test.tsx.snap
- src/components/templates/ErrorPages/Four0Four/__snapshots__/Four0Four.test.tsx.snap
Improvement to button pressed state logic
This commit modifies the Button component to prevent hover styles from
being applied when the button is in an active state. This is achieved
by adding a :not(:active) pseudo-class to the existing :hover 
pseudo-class in the button's CSS.
> Button pressed state

- .changeset/long-beds-compete.md
- src/components/atoms/ErrorMessage/ErrorMessage.tsx
- src/components/organisms/Form/FormSection/__snapshots__/FormSection.test.tsx.snap
- src/components/styles/Theme/ThemeProvider.tsx
- src/components/styles/icons/circleExclamation2.tsx
> Error msg icon2

- .changeset/grumpy-timers-judge.md
- src/components/molecules/ZopaFooter/ZopaFooter.tsx
- src/components/molecules/ZopaFooter/__snapshots__/ZopaFooter.test.tsx.snap
Added the new footer link
https://jira.zopa/browse/WEBP-6650
> WEBP-6650: Added the new footer link
